#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Vsd_Temp_Country
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Afghanistan", 0)]
		Afghanistan = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Albania", 1)]
		Albania = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Algeria", 2)]
		Algeria = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Andorra", 3)]
		Andorra = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Angola", 4)]
		Angola = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Anguilla", 7, "#0000ff")]
		Anguilla = 100000200,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Antarctica", 5, "#0000ff")]
		Antarctica = 100000202,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Antigua and Barbuda", 6)]
		AntiguaAndBarbuda = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Argentina", 8)]
		Argentina = 100000006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Armenia", 9)]
		Armenia = 100000007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Aruba", 10, "#0000ff")]
		Aruba = 100000203,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Australia", 11)]
		Australia = 100000008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Austria", 12)]
		Austria = 100000009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Azerbaijan", 13)]
		Azerbaijan = 100000010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Bahamas", 14)]
		Bahamas = 100000011,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Bahrain", 15)]
		Bahrain = 100000012,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Bangladesh", 16)]
		Bangladesh = 100000013,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Barbados", 17)]
		Barbados = 100000014,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Belarus", 18)]
		Belarus = 100000015,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Belgium", 19)]
		Belgium = 100000016,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Belize", 20)]
		Belize = 100000017,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Benin", 21)]
		Benin = 100000018,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Bermuda", 22, "#0000ff")]
		Bermuda = 100000205,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Bhutan", 23)]
		Bhutan = 100000019,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Bolivia", 24)]
		Bolivia = 100000020,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Bonaire", 25, "#0000ff")]
		Bonaire = 100000206,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Bosnia and Herzegovina", 27)]
		BosniaAndHerzegovina = 100000021,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Botswana", 28)]
		Botswana = 100000022,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Bouvet Island", 26, "#0000ff")]
		BouvetIsland = 100000207,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Brazil", 29)]
		Brazil = 100000023,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("British Indian Ocean Territory", 30, "#0000ff")]
		BritishIndianOceanTerritory = 100000225,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("British Virgin Islands", 31, "#0000ff")]
		BritishVirginIslands = 100000248,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Brunei", 32)]
		Brunei = 100000024,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Bulgaria", 33)]
		Bulgaria = 100000025,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Burkina Faso", 34)]
		BurkinaFaso = 100000026,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Burundi", 35)]
		Burundi = 100000027,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Cambodia", 37)]
		Cambodia = 100000029,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Cameroon", 38)]
		Cameroon = 100000030,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Canada", 39)]
		Canada = 100000031,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Cape Verde", 36)]
		CapeVerde = 100000028,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Cayman Islands", 40)]
		CaymanIslands = 100000032,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Central African Republic", 41)]
		CentralAfricanRepublic = 100000033,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Chad", 42)]
		Chad = 100000034,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Chile", 43)]
		Chile = 100000035,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("China", 44)]
		China = 100000036,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Christmas Island", 45, "#0000ff")]
		ChristmasIsland = 100000211,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Cocos Islands", 46, "#0000ff")]
		CocosIslands = 100000208,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Colombia", 49)]
		Colombia = 100000037,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Comoros", 50)]
		Comoros = 100000038,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Cook Islands", 47, "#0000ff")]
		CookIslands = 100000209,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Costa Rica", 51)]
		CostaRica = 100000039,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Côte d\'Ivoire", 52)]
		CoteDIvoire = 100000040,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Croatia", 53)]
		Croatia = 100000041,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Cuba", 54)]
		Cuba = 100000042,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Curacao", 48, "#0000ff")]
		Curacao = 100000210,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Cyprus", 55)]
		Cyprus = 100000043,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Czech Republic", 56)]
		CzechRepublic = 100000044,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Democratic Republic of the Congo", 57)]
		DemocraticRepublicOfTheCongo = 100000045,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Denmark", 58)]
		Denmark = 100000046,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Djibouti", 59)]
		Djibouti = 100000047,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dominica", 60)]
		Dominica = 100000048,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dominican Republic", 61)]
		DominicanRepublic = 100000049,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("East Timor", 62, "#0000ff")]
		EastTimor = 100000246,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ecuador", 63)]
		Ecuador = 100000050,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Egypt", 64)]
		Egypt = 100000051,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("El Salvador", 65)]
		ElSalvador = 100000052,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("England", 66)]
		England = 100000053,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Equatorial Guinea", 67)]
		EquatorialGuinea = 100000054,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Eritrea", 68)]
		Eritrea = 100000055,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Estonia", 69)]
		Estonia = 100000056,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Eswatini", 70)]
		Eswatini = 100000057,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ethiopia", 71)]
		Ethiopia = 100000058,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Falkland Islands", 72, "#0000ff")]
		FalklandIslands = 100000213,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Faroe Islands", 73, "#0000ff")]
		FaroeIslands = 100000214,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Fiji", 74)]
		Fiji = 100000059,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Finland", 75)]
		Finland = 100000060,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("France", 76)]
		France = 100000061,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("France Metropolitan", 77, "#0000ff")]
		FranceMetropolitan = 100000215,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("French Guiana", 78, "#0000ff")]
		FrenchGuiana = 100000216,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("French Polynesia", 79, "#0000ff")]
		FrenchPolynesia = 100000235,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("French Southern Territories", 80, "#0000ff")]
		FrenchSouthernTerritories = 100000244,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Gabon", 81)]
		Gabon = 100000062,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Gambia", 82)]
		Gambia = 100000063,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Georgia", 83)]
		Georgia = 100000064,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Germany", 84)]
		Germany = 100000065,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ghana", 85)]
		Ghana = 100000066,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Gibraltar", 86, "#0000ff")]
		Gibraltar = 100000218,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Greece", 87)]
		Greece = 100000067,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Greenland", 88, "#0000ff")]
		Greenland = 100000219,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Grenada", 89)]
		Grenada = 100000068,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Guadelope", 91, "#0000ff")]
		Guadelope = 100000220,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Guatemala", 90)]
		Guatemala = 100000069,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Guernsey", 92, "#0000ff")]
		Guernsey = 100000217,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Guinea", 93)]
		Guinea = 100000070,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Guinea Bissau", 94)]
		GuineaBissau = 100000071,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Guyana", 95)]
		Guyana = 100000072,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Haiti", 96)]
		Haiti = 100000073,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Heard Islands and McDonald Islands", 99, "#0000ff")]
		HeardIslandsAndMcdonaldIslands = 100000223,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Honduras", 98)]
		Honduras = 100000075,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Hong Kong", 100, "#0000ff")]
		HongKong = 100000222,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Hungary", 101)]
		Hungary = 100000076,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Iceland", 102)]
		Iceland = 100000077,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("India", 103)]
		India = 100000078,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Indonesia", 104)]
		Indonesia = 100000079,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Iran", 105)]
		Iran = 100000080,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Iraq", 106)]
		Iraq = 100000081,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ireland", 107)]
		Ireland = 100000082,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ireland Northern", 108)]
		IrelandNorthern = 100000083,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Isle of Man", 110, "#0000ff")]
		IsleOfMan = 100000224,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Israel", 109)]
		Israel = 100000084,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Italy", 111)]
		Italy = 100000085,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Jamaica", 112)]
		Jamaica = 100000086,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Japan", 113)]
		Japan = 100000087,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Jersey", 114, "#0000ff")]
		Jersey = 100000226,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Jordan", 115)]
		Jordan = 100000088,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Kazakhstan", 116)]
		Kazakhstan = 100000089,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Kenya", 117)]
		Kenya = 100000090,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Kiribati", 118)]
		Kiribati = 100000091,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Korea", 119)]
		Korea = 100000092,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Kuwait", 120)]
		Kuwait = 100000093,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Kyrgyzstan", 121)]
		Kyrgyzstan = 100000094,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Laos", 122)]
		Laos = 100000095,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Latin America", 130)]
		LatinAmerica_100000102 = 100000102,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Latin America", 124, "#0000ff")]
		LatinAmerica_100000199 = 100000199,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Latvia", 123)]
		Latvia = 100000096,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Lebanon", 125)]
		Lebanon = 100000097,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Lesotho", 126)]
		Lesotho = 100000098,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Liberia", 127)]
		Liberia = 100000099,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Libya", 128)]
		Libya = 100000100,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Liechtenstein", 129)]
		Liechtenstein = 100000101,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Luxembourg", 131)]
		Luxembourg = 100000103,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Macau", 132, "#0000ff")]
		Macau = 100000228,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Madagascar", 133)]
		Madagascar = 100000104,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Malawi", 134)]
		Malawi = 100000105,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Malaysia", 135)]
		Malaysia = 100000106,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Maldives", 136)]
		Maldives = 100000107,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Mali", 137)]
		Mali = 100000108,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Malta", 138)]
		Malta = 100000109,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Marshall Islands", 139)]
		MarshallIslands = 100000110,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Martinique", 140, "#0000ff")]
		Martinique = 100000230,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Mauritania", 141)]
		Mauritania = 100000111,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Mauritius", 142)]
		Mauritius = 100000112,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Mayotte", 143, "#0000ff")]
		Mayotte = 100000251,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Mexico", 144)]
		Mexico = 100000113,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Micronesia", 145)]
		Micronesia = 100000114,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Moldova", 146)]
		Moldova = 100000115,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Monaco", 147)]
		Monaco = 100000116,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Mongolia", 148)]
		Mongolia = 100000117,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Montenegro", 149)]
		Montenegro = 100000118,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Montserrat", 150, "#0000ff")]
		Montserrat = 100000231,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Morocco", 151)]
		Morocco = 100000119,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Mozambique", 152)]
		Mozambique = 100000120,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Myanmar", 153)]
		Myanmar = 100000121,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Namibia", 154)]
		Namibia = 100000122,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Nauru", 155)]
		Nauru = 100000123,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Nepal", 156)]
		Nepal = 100000124,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Netherlands", 157)]
		Netherlands = 100000125,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Netherlands Antilles", 158, "#0000ff")]
		NetherlandsAntilles = 100000201,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("New Caledonia", 160, "#0000ff")]
		NewCaledonia = 100000232,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("New Zealand", 159)]
		NewZealand = 100000126,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Nicaragua", 161)]
		Nicaragua = 100000127,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Niger", 162)]
		Niger = 100000128,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Nigeria", 163)]
		Nigeria = 100000129,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Niue", 164, "#0000ff")]
		Niue = 100000234,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Norfolk Island", 165, "#0000ff")]
		NorfolkIsland = 100000233,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Northern Mariana Islands", 168, "#0000ff")]
		NorthernMarianaIslands = 100000229,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("North Korea", 166)]
		NorthKorea = 100000130,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("North Macedonia", 167)]
		NorthMacedonia = 100000131,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Norway", 169)]
		Norway = 100000132,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Oman", 170)]
		Oman = 100000133,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Pakistan", 171)]
		Pakistan = 100000134,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Palau", 172)]
		Palau = 100000135,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Palestine State", 173)]
		PalestineState = 100000136,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Panama", 174)]
		Panama = 100000137,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Papua New Guinea", 175)]
		PapuaNewGuinea = 100000138,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Paraguay", 176)]
		Paraguay = 100000139,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Peru", 177)]
		Peru = 100000140,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Philippines", 179)]
		Philippines = 100000141,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Pitcairn", 178, "#0000ff")]
		Pitcairn = 100000237,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Poland", 180)]
		Poland = 100000142,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Portugal", 181)]
		Portugal = 100000143,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Puerto Rico", 182, "#0000ff")]
		PuertoRico = 100000238,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Qatar", 183)]
		Qatar = 100000144,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reunion", 184, "#0000ff")]
		Reunion = 100000239,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Romania", 185)]
		Romania = 100000145,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Russia", 186)]
		Russia = 100000146,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Rwanda", 187)]
		Rwanda = 100000147,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Saint Barthelemy", 191, "#0000ff")]
		SaintBarthelemy = 100000204,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Saint Helena", 194, "#0000ff")]
		SaintHelena = 100000240,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Saint Kitts and Nevis", 188)]
		SaintKittsAndNevis = 100000148,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Saint Lucia", 189)]
		SaintLucia = 100000149,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Saint Martin", 192, "#0000ff")]
		SaintMartin = 100000227,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Saint Pierre and Miquelontem", 193, "#0000ff")]
		SaintPierreAndMiquelontem = 100000236,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Saint Vincent and the Grenadines", 190)]
		SaintVincentAndTheGrenadines = 100000150,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Samoa", 197)]
		Samoa = 100000151,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("San Marino", 198)]
		SanMarino = 100000152,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sao Tome and Principe", 199)]
		SaoTomeAndPrincipe = 100000153,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Saudi Arabia", 200)]
		SaudiArabia = 100000154,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Scotland", 201)]
		Scotland = 100000155,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Senegal", 202)]
		Senegal = 100000156,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Serbia", 203)]
		Serbia = 100000157,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Seychelles", 204)]
		Seychelles = 100000158,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sierra Leone", 205)]
		SierraLeone = 100000159,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Singapore", 206)]
		Singapore = 100000160,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sint Maarten", 196, "#0000ff")]
		SintMaarten = 100000242,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Slovakia", 207)]
		Slovakia = 100000161,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Slovenia", 208)]
		Slovenia = 100000162,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Solomon Islands", 209)]
		SolomonIslands = 100000163,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Somalia", 210)]
		Somalia = 100000164,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("South Africa", 211)]
		SouthAfrica = 100000165,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("South Georgia and the South Sandwich Island", 212, "#0000ff")]
		SouthGeorgiaAndTheSouthSandwichIsland = 100000221,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("South Korea", 213)]
		SouthKorea = 100000166,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("South Sudan", 214)]
		SouthSudan = 100000167,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Spain", 215)]
		Spain = 100000168,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sri Lanka", 216)]
		SriLanka = 100000169,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sudan", 217)]
		Sudan = 100000170,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Suriname", 218)]
		Suriname = 100000171,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Svalbard and Jan Mayen Islands", 195, "#0000ff")]
		SvalbardAndJanMayenIslands = 100000241,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sweden", 219)]
		Sweden = 100000172,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Switzerland", 220)]
		Switzerland = 100000173,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Syria", 221)]
		Syria = 100000174,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Taiwan", 222, "#0000ff")]
		Taiwan = 100000247,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Tajikistan", 223)]
		Tajikistan = 100000175,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Tanzania", 224)]
		Tanzania = 100000176,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Thailand", 225)]
		Thailand = 100000177,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Timor-Leste", 226)]
		TimorLeste = 100000178,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Togo", 227)]
		Togo = 100000179,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Tokelau", 228, "#0000ff")]
		Tokelau = 100000245,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Tonga", 229)]
		Tonga = 100000180,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Trinidad and Tobago", 230)]
		TrinidadAndTobago = 100000181,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Tunisia", 231)]
		Tunisia = 100000182,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Turkey", 232)]
		Turkey = 100000183,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Turkmenistan", 233)]
		Turkmenistan = 100000184,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Turks and Caicos Islands", 234, "#0000ff")]
		TurksAndCaicosIslands = 100000243,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Tuvalu", 235)]
		Tuvalu = 100000185,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Uganda", 236)]
		Uganda = 100000186,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ukraine", 237)]
		Ukraine = 100000187,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("United Arab Emirates", 238)]
		UnitedArabEmirates = 100000188,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("United Kingdom", 239)]
		UnitedKingdom = 100000189,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("United States of America", 241)]
		UnitedStatesOfAmerica = 100000191,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Uruguay", 240)]
		Uruguay = 100000190,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("US Virgin Islands", 242, "#0000ff")]
		UsVirginIslands = 100000249,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Uzbekistan", 243)]
		Uzbekistan = 100000192,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Vanuatu", 244)]
		Vanuatu = 100000193,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Vatican City", 97)]
		VaticanCity = 100000074,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Venezuela", 245)]
		Venezuela = 100000194,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Vietnam", 246)]
		Vietnam = 100000195,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Wallis and Futuna Islands", 247, "#0000ff")]
		WallisAndFutunaIslands = 100000250,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Western Sahara", 248, "#0000ff")]
		WesternSahara = 100000212,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Yemen", 249)]
		Yemen = 100000196,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Yugoslavia", 250, "#0000ff")]
		Yugoslavia = 100000252,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Zaire", 251, "#0000ff")]
		Zaire = 100000253,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Zambia", 252)]
		Zambia = 100000197,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Zimbabwe", 253)]
		Zimbabwe = 100000198,
	}
}
#pragma warning restore CS1591
