#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Vsd_Vsu_ApplicantType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Civil Protected Party", 3, "#0000ff")]
		CivilProtectedParty = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("IFM of Deceased Victim", 7, "#0000ff")]
		IfmOfDeceasedVictim = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Other Family Member", 5, "#0000ff")]
		OtherFamilyMember = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Support Person", 6, "#0000ff")]
		SupportPerson = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Victim", 0, "#0000ff")]
		Victim = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Victim Service Worker", 2, "#0000ff")]
		VictimServiceWorker = 100000006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Victim\'s Parent / Guardian", 4, "#0000ff")]
		VictimsParentGuardian = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("VISTA Record", 1, "#0000ff")]
		VistaRecord = 100000007,
	}
}
#pragma warning restore CS1591
