#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Vsd_RestCustodyLocations
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("F - Fraser Valley Institution (Multi)", 11, "#0000ff")]
		FFraserValleyInstitutionMulti = 100000010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("F - Kent Institution (Max)", 12, "#0000ff")]
		FKentInstitutionMax = 100000011,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("F - Kwìkwèxwelhp Healing Village (Min)", 13, "#0000ff")]
		FKwikwexwelhpHealingVillageMin = 100000012,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("F - Matsqui Institution (Med)", 14, "#0000ff")]
		FMatsquiInstitutionMed = 100000013,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("F - Mission Institution (Med)", 15, "#0000ff")]
		FMissionInstitutionMed = 100000014,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("F - Mission Institution (Min)", 16, "#0000ff")]
		FMissionInstitutionMin = 100000015,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("F - Mountain Institution (Med)", 17, "#0000ff")]
		FMountainInstitutionMed = 100000016,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("F - Pacific Institution / Regional Treatment Centre (Multi)", 18, "#0000ff")]
		FPacificInstitutionRegionalTreatmentCentreMulti = 100000017,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("F - Unknown", 20, "#0000ff")]
		FUnknown = 100000020,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("F - William Head Institution (Min)", 19, "#0000ff")]
		FWilliamHeadInstitutionMin = 100000018,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("P - Alouette Correctional Centre for Women", 0, "#0000ff")]
		PAlouetteCorrectionalCentreForWomen = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("P - Ford Mountain Correctional Centre", 1, "#0000ff")]
		PFordMountainCorrectionalCentre = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("P - Fraser Regional Correctional Centre", 2, "#0000ff")]
		PFraserRegionalCorrectionalCentre = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("P - Kamloops Regional Correctional Centre", 3, "#0000ff")]
		PKamloopsRegionalCorrectionalCentre = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("P - Nanaimo Correctional Centre", 4, "#0000ff")]
		PNanaimoCorrectionalCentre = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("P - North Fraser Pretrial Centre", 5, "#0000ff")]
		PNorthFraserPretrialCentre = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("P - Okanagan Correctional Centre", 6, "#0000ff")]
		POkanaganCorrectionalCentre = 100000006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("P - Prince George Regional Correctional Centre", 7, "#0000ff")]
		PPrinceGeorgeRegionalCorrectionalCentre = 100000007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("P - Surrey Pretrial Services Centre", 8, "#0000ff")]
		PSurreyPretrialServicesCentre = 100000008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("P - Unknown", 10, "#0000ff")]
		PUnknown = 100000019,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("P - Vancouver Island Regional Correctional Centre", 9, "#0000ff")]
		PVancouverIslandRegionalCorrectionalCentre = 100000009,
	}
}
#pragma warning restore CS1591
