#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Vsd_ProcurementCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("100 - Open Competitive Process", 0, "#0000ff")]
		_100OpenCompetitiveProcess = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("200 - Direct Award - Public Sector Organization", 1, "#0000ff")]
		_200DirectAwardPublicSectorOrganization = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("201 - Direct Award - Sole Source", 2, "#0000ff")]
		_201DirectAwardSoleSource = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("205 - Direct Award - Notice of Intent", 3, "#0000ff")]
		_205DirectAwardNoticeOfIntent = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("208 - Shared Cost Arrangement (Financial Assistance)", 4, "#0000ff")]
		_208SharedCostArrangementFinancialAssistance = 100000007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("209 - Shared Cost Arrangement (Competitive Selection Process Not Appropriate)", 5, "#0000ff")]
		_209SharedCostArrangementCompetitiveSelectionProcessNotAppropriate = 100000008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("400 - Select Vendor from Pre-Qualification List", 6, "#0000ff")]
		_400SelectVendorFromPreQualificationList = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("401 - Competition Among Vendors on a Pre-Qualification List", 7, "#0000ff")]
		_401CompetitionAmongVendorsOnAPreQualificationList = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("500 - Purchase from a Corporate Supply Arrangement", 8, "#0000ff")]
		_500PurchaseFromACorporateSupplyArrangement = 100000006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("600 - Continuing Agreement", 9, "#0000ff")]
		_600ContinuingAgreement = 100000009,
	}
}
#pragma warning restore CS1591
