#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Vsd_Vsu_NotificationTo
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("My designate only on my behalf", 1, "#0000ff")]
		MyDesignateOnlyOnMyBehalf = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("My designate plus my victim service worker", 5, "#0000ff")]
		MyDesignatePlusMyVictimServiceWorker = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Myself only", 0, "#0000ff")]
		MyselfOnly = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Myself plus my designate", 3, "#0000ff")]
		MyselfPlusMyDesignate = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Myself plus my victim service worker", 4, "#0000ff")]
		MyselfPlusMyVictimServiceWorker = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("My victim service worker only on my behalf", 2, "#0000ff")]
		MyVictimServiceWorkerOnlyOnMyBehalf = 100000002,
	}
}
#pragma warning restore CS1591
