def PIPELINE_NAME = "deployment/bc-test"

def LIB_NAME= "vsd-lib"
def LIB_REPO = "https://github.com/bcgov/pssg-cscp-vsd.git"
def LIB_BRANCH = "development"

library identifier: "${LIB_NAME}@${LIB_BRANCH}", 
        retriever: modernSCM(
          [$class: 'GitSCMSource',
          remote: "${LIB_REPO}",
          branches: [[name: "*/${LIB_BRANCH}"]]])  

node {
  def config = load "../workspace@script/jenkins/${PIPELINE_NAME}/config.groovy"
        
  config.APPS.each { appName ->
    stage("Deploying ${appName} to ${config.DESTINATION_TAG}") {
      script {
        openshift.withCluster() {
          openshift.withProject() {
            echo "JTT: Tagging ${appName}:${config.SOURCE_TAG} for deployment to ${config.DESTINATION_TAG} ..."
            openshift.tag("${appName}:${config.SOURCE_TAG}", "${appName}:${config.DESTINATION_TAG}")
            echo "JTT: Done tagging"
          }
        }
      }
    }
  }
  stage("Deploy ${config.DEPLOYMENT_ENVIRONMENT_TAGS[0]}") {
    script {
      deploy("pssg-cscp",
             "-vsd",
             "dev",
             "latest")
    }
  }}
