/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * VSD API
 * API for the Victim Services Directory (VSD) application
 * OpenAPI spec version: v1
 */
import type {
  HttpResponse as AngularHttpResponse,
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams
} from '@angular/common/http';
import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import type { GetApiLookupCitiesSearchParams } from '../../model';

type HttpClientOptions = {
  headers?:
    | HttpHeaders
    | {
        [header: string]: string | string[];
      };
  context?: HttpContext;
  observe?: any;
  params?:
    | HttpParams
    | {
        [param: string]: string | number | boolean | ReadonlyArray<string | number | boolean>;
      };
  reportProgress?: boolean;
  responseType?: any;
  withCredentials?: boolean;
};

@Injectable({ providedIn: 'root' })
export class LookupService {
  constructor(private http: HttpClient) {}
  getApiLookupCvapEmails<TData = void>(
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
  getApiLookupCvapEmails<TData = void>(
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  getApiLookupCvapEmails<TData = void>(
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;
  getApiLookupCvapEmails<TData = void>(options?: HttpClientOptions): Observable<TData> {
    return this.http.get<TData>(`/cvapwebform/api/Lookup/cvap-emails`, options);
  }
  getApiLookupCountries<TData = void>(
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
  getApiLookupCountries<TData = void>(
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  getApiLookupCountries<TData = void>(
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;
  getApiLookupCountries<TData = void>(options?: HttpClientOptions): Observable<TData> {
    return this.http.get<TData>(`/cvapwebform/api/Lookup/countries`, options);
  }
  getApiLookupProvinces<TData = void>(
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
  getApiLookupProvinces<TData = void>(
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  getApiLookupProvinces<TData = void>(
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;
  getApiLookupProvinces<TData = void>(options?: HttpClientOptions): Observable<TData> {
    return this.http.get<TData>(`/cvapwebform/api/Lookup/provinces`, options);
  }
  getApiLookupCities<TData = void>(
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
  getApiLookupCities<TData = void>(
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  getApiLookupCities<TData = void>(
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;
  getApiLookupCities<TData = void>(options?: HttpClientOptions): Observable<TData> {
    return this.http.get<TData>(`/cvapwebform/api/Lookup/cities`, options);
  }
  getApiLookupCitiesSearch<TData = void>(
    params?: GetApiLookupCitiesSearchParams,
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
  getApiLookupCitiesSearch<TData = void>(
    params?: GetApiLookupCitiesSearchParams,
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  getApiLookupCitiesSearch<TData = void>(
    params?: GetApiLookupCitiesSearchParams,
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;
  getApiLookupCitiesSearch<TData = void>(
    params?: GetApiLookupCitiesSearchParams,
    options?: HttpClientOptions
  ): Observable<TData> {
    return this.http.get<TData>(`/cvapwebform/api/Lookup/cities/search`, {
      ...options,
      params: { ...params, ...options?.params }
    });
  }
  getApiLookupCountryCountryCities<TData = void>(
    country: string,
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
  getApiLookupCountryCountryCities<TData = void>(
    country: string,
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  getApiLookupCountryCountryCities<TData = void>(
    country: string,
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;
  getApiLookupCountryCountryCities<TData = void>(country: string, options?: HttpClientOptions): Observable<TData> {
    return this.http.get<TData>(`/cvapwebform/api/Lookup/country/${country}/cities`, options);
  }
  getApiLookupCountryCountryIdProvinceProvinceIdCities<TData = void>(
    countryId: string,
    provinceId: string,
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
  getApiLookupCountryCountryIdProvinceProvinceIdCities<TData = void>(
    countryId: string,
    provinceId: string,
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  getApiLookupCountryCountryIdProvinceProvinceIdCities<TData = void>(
    countryId: string,
    provinceId: string,
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;
  getApiLookupCountryCountryIdProvinceProvinceIdCities<TData = void>(
    countryId: string,
    provinceId: string,
    options?: HttpClientOptions
  ): Observable<TData> {
    return this.http.get<TData>(`/cvapwebform/api/Lookup/country/${countryId}/province/${provinceId}/cities`, options);
  }
  getApiLookupRelationships<TData = void>(
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
  getApiLookupRelationships<TData = void>(
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  getApiLookupRelationships<TData = void>(
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;
  getApiLookupRelationships<TData = void>(options?: HttpClientOptions): Observable<TData> {
    return this.http.get<TData>(`/cvapwebform/api/Lookup/relationships`, options);
  }
  getApiLookupAuthRelationships<TData = void>(
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
  getApiLookupAuthRelationships<TData = void>(
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  getApiLookupAuthRelationships<TData = void>(
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;
  getApiLookupAuthRelationships<TData = void>(options?: HttpClientOptions): Observable<TData> {
    return this.http.get<TData>(`/cvapwebform/api/Lookup/auth_relationships`, options);
  }
  getApiLookupRepresentativeRelationships<TData = void>(
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
  getApiLookupRepresentativeRelationships<TData = void>(
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  getApiLookupRepresentativeRelationships<TData = void>(
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;
  getApiLookupRepresentativeRelationships<TData = void>(options?: HttpClientOptions): Observable<TData> {
    return this.http.get<TData>(`/cvapwebform/api/Lookup/representative_relationships`, options);
  }
  getApiLookupImfRepresentativeRelationships<TData = void>(
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
  getApiLookupImfRepresentativeRelationships<TData = void>(
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  getApiLookupImfRepresentativeRelationships<TData = void>(
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;
  getApiLookupImfRepresentativeRelationships<TData = void>(options?: HttpClientOptions): Observable<TData> {
    return this.http.get<TData>(`/cvapwebform/api/Lookup/imf_representative_relationships`, options);
  }
  getApiLookupPoliceDetachments<TData = void>(
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
  getApiLookupPoliceDetachments<TData = void>(
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  getApiLookupPoliceDetachments<TData = void>(
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;
  getApiLookupPoliceDetachments<TData = void>(options?: HttpClientOptions): Observable<TData> {
    return this.http.get<TData>(`/cvapwebform/api/Lookup/police_detachments`, options);
  }
  getApiLookupCourts<TData = void>(
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
  getApiLookupCourts<TData = void>(
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  getApiLookupCourts<TData = void>(
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;
  getApiLookupCourts<TData = void>(options?: HttpClientOptions): Observable<TData> {
    return this.http.get<TData>(`/cvapwebform/api/Lookup/courts`, options);
  }
}

export type GetApiLookupCvapEmailsClientResult = NonNullable<void>;
export type GetApiLookupCountriesClientResult = NonNullable<void>;
export type GetApiLookupProvincesClientResult = NonNullable<void>;
export type GetApiLookupCitiesClientResult = NonNullable<void>;
export type GetApiLookupCitiesSearchClientResult = NonNullable<void>;
export type GetApiLookupCountryCountryCitiesClientResult = NonNullable<void>;
export type GetApiLookupCountryCountryIdProvinceProvinceIdCitiesClientResult = NonNullable<void>;
export type GetApiLookupRelationshipsClientResult = NonNullable<void>;
export type GetApiLookupAuthRelationshipsClientResult = NonNullable<void>;
export type GetApiLookupRepresentativeRelationshipsClientResult = NonNullable<void>;
export type GetApiLookupImfRepresentativeRelationshipsClientResult = NonNullable<void>;
export type GetApiLookupPoliceDetachmentsClientResult = NonNullable<void>;
export type GetApiLookupCourtsClientResult = NonNullable<void>;
