/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * VSD API
 * API for the Victim Services Directory (VSD) application
 * OpenAPI spec version: v1
 */
import type {
  HttpResponse as AngularHttpResponse,
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams
} from '@angular/common/http';
import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import type { ApplicationFormModel, CounsellorInvoiceFormModel } from '../../model';

type HttpClientOptions = {
  headers?:
    | HttpHeaders
    | {
        [header: string]: string | string[];
      };
  context?: HttpContext;
  observe?: any;
  params?:
    | HttpParams
    | {
        [param: string]: string | number | boolean | ReadonlyArray<string | number | boolean>;
      };
  reportProgress?: boolean;
  responseType?: any;
  withCredentials?: boolean;
};

@Injectable({ providedIn: 'root' })
export class AemService {
  constructor(private http: HttpClient) {}
  postApiAEMVictim<TData = void>(
    applicationFormModel: ApplicationFormModel,
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
  postApiAEMVictim<TData = void>(
    applicationFormModel: ApplicationFormModel,
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  postApiAEMVictim<TData = void>(
    applicationFormModel: ApplicationFormModel,
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;
  postApiAEMVictim<TData = void>(
    applicationFormModel: ApplicationFormModel,
    options?: HttpClientOptions
  ): Observable<TData> {
    return this.http.post<TData>(`/api/AEM/victim`, applicationFormModel, options);
  }
  postApiAEMIfm<TData = void>(
    applicationFormModel: ApplicationFormModel,
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
  postApiAEMIfm<TData = void>(
    applicationFormModel: ApplicationFormModel,
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  postApiAEMIfm<TData = void>(
    applicationFormModel: ApplicationFormModel,
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;
  postApiAEMIfm<TData = void>(
    applicationFormModel: ApplicationFormModel,
    options?: HttpClientOptions
  ): Observable<TData> {
    return this.http.post<TData>(`/api/AEM/ifm`, applicationFormModel, options);
  }
  postApiAEMWitness<TData = void>(
    applicationFormModel: ApplicationFormModel,
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
  postApiAEMWitness<TData = void>(
    applicationFormModel: ApplicationFormModel,
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  postApiAEMWitness<TData = void>(
    applicationFormModel: ApplicationFormModel,
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;
  postApiAEMWitness<TData = void>(
    applicationFormModel: ApplicationFormModel,
    options?: HttpClientOptions
  ): Observable<TData> {
    return this.http.post<TData>(`/api/AEM/witness`, applicationFormModel, options);
  }
  postApiAEMAuthorization<TData = void>(
    applicationFormModel: ApplicationFormModel,
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
  postApiAEMAuthorization<TData = void>(
    applicationFormModel: ApplicationFormModel,
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  postApiAEMAuthorization<TData = void>(
    applicationFormModel: ApplicationFormModel,
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;
  postApiAEMAuthorization<TData = void>(
    applicationFormModel: ApplicationFormModel,
    options?: HttpClientOptions
  ): Observable<TData> {
    return this.http.post<TData>(`/api/AEM/authorization`, applicationFormModel, options);
  }
  postApiAEMInvoice<TData = void>(
    counsellorInvoiceFormModel: CounsellorInvoiceFormModel,
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
  postApiAEMInvoice<TData = void>(
    counsellorInvoiceFormModel: CounsellorInvoiceFormModel,
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  postApiAEMInvoice<TData = void>(
    counsellorInvoiceFormModel: CounsellorInvoiceFormModel,
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;
  postApiAEMInvoice<TData = void>(
    counsellorInvoiceFormModel: CounsellorInvoiceFormModel,
    options?: HttpClientOptions
  ): Observable<TData> {
    return this.http.post<TData>(`/api/AEM/invoice`, counsellorInvoiceFormModel, options);
  }
  getApiAEMGeneratePdfTypeApplicationId<TData = void>(
    pdfType: string,
    applicationId: string,
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
  getApiAEMGeneratePdfTypeApplicationId<TData = void>(
    pdfType: string,
    applicationId: string,
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  getApiAEMGeneratePdfTypeApplicationId<TData = void>(
    pdfType: string,
    applicationId: string,
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;
  getApiAEMGeneratePdfTypeApplicationId<TData = void>(
    pdfType: string,
    applicationId: string,
    options?: HttpClientOptions
  ): Observable<TData> {
    return this.http.get<TData>(`/api/AEM/generate/${pdfType}/${applicationId}`, options);
  }
}

export type PostApiAEMVictimClientResult = NonNullable<void>;
export type PostApiAEMIfmClientResult = NonNullable<void>;
export type PostApiAEMWitnessClientResult = NonNullable<void>;
export type PostApiAEMAuthorizationClientResult = NonNullable<void>;
export type PostApiAEMInvoiceClientResult = NonNullable<void>;
export type GetApiAEMGeneratePdfTypeApplicationIdClientResult = NonNullable<void>;
