#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	/// <summary>
	/// Status of the Schedule G
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Vsd_ScheduleG_StateCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Active", 0)]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inactive", 1)]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Schedule G
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Vsd_ScheduleG_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Approved", 3, "#0000ff")]
		Approved = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Archived", 5, "#0000ff")]
		Archived = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Information Denied", 4, "#0000ff")]
		InformationDenied = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Processing", 2, "#0000ff")]
		Processing = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Received", 1, "#0000ff")]
		Received = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sent", 0, "#0000ff")]
		Sent = 1,
	}
	
	/// <summary>
	/// The submitted schedule G quarterly report.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Vsd_ScheduleG_Vsd_Cpu_ReportingPeriod
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("1st Quarter", 0, "#0000ff")]
		_1stQuarter = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("2nd Quarter", 1, "#0000ff")]
		_2ndQuarter = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("3rd Quarter", 2, "#0000ff")]
		_3rdQuarter = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("4th Quarter", 3, "#0000ff")]
		_4thQuarter = 100000003,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("vsd_scheduleg")]
	public partial class Vsd_ScheduleG : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the vsd_scheduleg entity
		/// </summary>
		public partial class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedByName = "createdbyname";
			public const string CreatedByYomiName = "createdbyyominame";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CreatedOnBehalfByName = "createdonbehalfbyname";
			public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
			public const string ExchangerAte = "exchangerate";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string Lk_Vsd_ScheduleG_CreatedBy = "lk_vsd_scheduleg_createdby";
			public const string Lk_Vsd_ScheduleG_CreatedOnBehalfBy = "lk_vsd_scheduleg_createdonbehalfby";
			public const string Lk_Vsd_ScheduleG_ModifiedBy = "lk_vsd_scheduleg_modifiedby";
			public const string Lk_Vsd_ScheduleG_ModifiedOnBehalfBy = "lk_vsd_scheduleg_modifiedonbehalfby";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedByName = "modifiedbyname";
			public const string ModifiedByYomiName = "modifiedbyyominame";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
			public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwnerIdName = "owneridname";
			public const string OwnerIdYomiName = "owneridyominame";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string StateCode = "statecode";
			public const string StateCodename = "statecodename";
			public const string StatusCode = "statuscode";
			public const string StatusCodename = "statuscodename";
			public const string Team_Vsd_ScheduleG = "team_vsd_scheduleg";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string TransactionCurrency_Vsd_ScheduleG = "TransactionCurrency_vsd_scheduleg";
			public const string TransactionCurrencyId = "transactioncurrencyid";
			public const string TransactionCurrencyIdName = "transactioncurrencyidname";
			public const string User_Vsd_ScheduleG = "user_vsd_scheduleg";
			public const string UtcConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string Vsd_Account_Vsd_ScheduleG_ServiceProvider = "vsd_account_vsd_scheduleg_ServiceProvider";
			public const string Vsd_ActualHoursThisQuarter = "vsd_actualhoursthisquarter";
			public const string Vsd_Contact = "vsd_contact";
			public const string Vsd_Contact_Vsd_ScheduleG_Contact = "vsd_contact_vsd_scheduleg_Contact";
			public const string Vsd_ContactName = "vsd_contactname";
			public const string Vsd_ContactYomiName = "vsd_contactyominame";
			public const string Vsd_Contract = "vsd_contract";
			public const string Vsd_ContractedServiceHrsThisQuarter = "vsd_contractedservicehrsthisquarter";
			public const string Vsd_ContractName = "vsd_contractname";
			public const string Vsd_Cpu_FiscalYear = "vsd_cpu_fiscalyear";
			public const string Vsd_Cpu_ReportingPeriod = "vsd_cpu_reportingperiod";
			public const string Vsd_Cpu_ReportingPeriodName = "vsd_cpu_reportingperiodname";
			public const string Vsd_Name = "vsd_name";
			public const string Vsd_Program = "vsd_program";
			public const string Vsd_ProgramAdministrationBudgeted = "vsd_programadministrationbudgeted";
			public const string Vsd_ProgramAdministrationBudgeted_Base = "vsd_programadministrationbudgeted_base";
			public const string Vsd_ProgramAdministrationCurrentQuarter = "vsd_programadministrationcurrentquarter";
			public const string Vsd_ProgramAdministrationCurrentQuarter_Base = "vsd_programadministrationcurrentquarter_base";
			public const string Vsd_ProgramAdministrationExplanation = "vsd_programadministrationexplanation";
			public const string Vsd_ProgramDeliveryBudgeted = "vsd_programdeliverybudgeted";
			public const string Vsd_ProgramDeliveryBudgeted_Base = "vsd_programdeliverybudgeted_base";
			public const string Vsd_ProgramDeliveryCurrentQuarter = "vsd_programdeliverycurrentquarter";
			public const string Vsd_ProgramDeliveryCurrentQuarter_Base = "vsd_programdeliverycurrentquarter_base";
			public const string Vsd_ProgramDeliveryExplanations = "vsd_programdeliveryexplanations";
			public const string Vsd_ProgramName = "vsd_programname";
			public const string Vsd_QuarterlyBudgetedProgramAdministration = "vsd_quarterlybudgetedprogramadministration";
			public const string Vsd_QuarterlyBudgetedProgramAdministration_Base = "vsd_quarterlybudgetedprogramadministration_base";
			public const string Vsd_QuarterlyBudgetedProgramDelivery = "vsd_quarterlybudgetedprogramdelivery";
			public const string Vsd_QuarterlyBudgetedProgramDelivery_Base = "vsd_quarterlybudgetedprogramdelivery_base";
			public const string Vsd_QuarterlyBudgetedSalariesBenefits = "vsd_quarterlybudgetedsalariesbenefits";
			public const string Vsd_QuarterlyBudgetedSalariesBenefits_Base = "vsd_quarterlybudgetedsalariesbenefits_base";
			public const string Vsd_QuarterlyVarianceProgramAdministration = "vsd_quarterlyvarianceprogramadministration";
			public const string Vsd_QuarterlyVarianceProgramAdministration_Base = "vsd_quarterlyvarianceprogramadministration_base";
			public const string Vsd_QuarterlyVarianceProgramDelivery = "vsd_quarterlyvarianceprogramdelivery";
			public const string Vsd_QuarterlyVarianceProgramDelivery_Base = "vsd_quarterlyvarianceprogramdelivery_base";
			public const string Vsd_QuarterlyVarianceSalariesBenefits = "vsd_quarterlyvariancesalariesbenefits";
			public const string Vsd_QuarterlyVarianceSalariesBenefits_Base = "vsd_quarterlyvariancesalariesbenefits_base";
			public const string Vsd_ReportReviewed = "vsd_reportreviewed";
			public const string Vsd_ReportReviewedName = "vsd_reportreviewedname";
			public const string Vsd_SalariesAndBenefitsExplanation = "vsd_salariesandbenefitsexplanation";
			public const string Vsd_SalariesBenefitsCurrentQuarter = "vsd_salariesbenefitscurrentquarter";
			public const string Vsd_SalariesBenefitsCurrentQuarter_Base = "vsd_salariesbenefitscurrentquarter_base";
			public const string Vsd_SalaryAndBenefitsBudgeted = "vsd_salaryandbenefitsbudgeted";
			public const string Vsd_SalaryAndBenefitsBudgeted_Base = "vsd_salaryandbenefitsbudgeted_base";
			public const string Vsd_ScheduleGId = "vsd_schedulegid";
			public const string Id = "vsd_schedulegid";
			public const string Vsd_ServiceProvider = "vsd_serviceprovider";
			public const string Vsd_ServiceProviderName = "vsd_serviceprovidername";
			public const string Vsd_ServiceProviderYomiName = "vsd_serviceprovideryominame";
			public const string Vsd_SubmittedDate = "vsd_submitteddate";
			public const string Vsd_SuMoFallYearToDateVariances = "vsd_sumofallyeartodatevariances";
			public const string Vsd_SuMoFallYearToDateVariances_Base = "vsd_sumofallyeartodatevariances_base";
			public const string Vsd_Vsd_Contract_Vsd_ScheduleG_Contract = "vsd_vsd_contract_vsd_scheduleg_Contract";
			public const string Vsd_Vsd_Program_Vsd_ScheduleG_Program = "vsd_vsd_program_vsd_scheduleg_Program";
			public const string Vsd_Vsd_ScheduleG_Task = "Vsd_Vsd_ScheduleG_Task";
			public const string Vsd_YearToDateProgramAdministration = "vsd_yeartodateprogramadministration";
			public const string Vsd_YearToDateProgramAdministration_Base = "vsd_yeartodateprogramadministration_base";
			public const string Vsd_YearToDateProgramDelivery = "vsd_yeartodateprogramdelivery";
			public const string Vsd_YearToDateProgramDelivery_Base = "vsd_yeartodateprogramdelivery_base";
			public const string Vsd_YearToDatesAlAriesAndBenefits = "vsd_yeartodatesalariesandbenefits";
			public const string Vsd_YearToDatesAlAriesAndBenefits_Base = "vsd_yeartodatesalariesandbenefits_base";
			public const string Vsd_YearToDateVarianceProgramAdministration = "vsd_yeartodatevarianceprogramadministration";
			public const string Vsd_YearToDateVarianceProgramAdministration_Base = "vsd_yeartodatevarianceprogramadministration_base";
			public const string Vsd_YearToDateVarianceProgramDelivery = "vsd_yeartodatevarianceprogramdelivery";
			public const string Vsd_YearToDateVarianceProgramDelivery_Base = "vsd_yeartodatevarianceprogramdelivery_base";
			public const string Vsd_YearToDateVarianceSalariesBenefits = "vsd_yeartodatevariancesalariesbenefits";
			public const string Vsd_YearToDateVarianceSalariesBenefits_Base = "vsd_yeartodatevariancesalariesbenefits_base";
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public Vsd_ScheduleG(System.Guid id) : 
				base(EntityLogicalName, id)
		{
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public Vsd_ScheduleG(string keyName, object keyValue) : 
				base(EntityLogicalName, keyName, keyValue)
		{
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public Vsd_ScheduleG(Microsoft.Xrm.Sdk.KeyAttributeCollection keyAttributes) : 
				base(EntityLogicalName, keyAttributes)
		{
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public Vsd_ScheduleG() : 
				base(EntityLogicalName)
		{
		}
		
		public const string PrimaryIdAttribute = "vsd_schedulegid";
		
		public const string PrimaryNameAttribute = "vsd_name";
		
		public const string EntitySchemaName = "vsd_scheduleg";
		
		public const string EntityLogicalName = "vsd_scheduleg";
		
		public const string EntityLogicalCollectionName = "vsd_schedulegs";
		
		public const string EntitySetName = "vsd_schedulegs";
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyname")]
		public string CreatedByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyyominame")]
		public string CreatedByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("createdonbehalfby", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyname")]
		public string CreatedOnBehalfByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
		public string CreatedOnBehalfByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Exchange rate for the currency associated with the entity with respect to the base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangerAte
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyname")]
		public string ModifiedByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyyominame")]
		public string ModifiedByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("modifiedonbehalfby", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
		public string ModifiedOnBehalfByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
		public string ModifiedOnBehalfByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridname")]
		public string OwnerIdName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Yomi name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridyominame")]
		public string OwnerIdYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Schedule G
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual Vsd_ScheduleG_StateCode? StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((Vsd_ScheduleG_StateCode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecodename")]
		public string StateCodename
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("statecode"))
				{
					return this.FormattedValues["statecode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Reason for the status of the Schedule G
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual Vsd_ScheduleG_StatusCode? StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((Vsd_ScheduleG_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscodename")]
		public string StatusCodename
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("statuscode"))
				{
					return this.FormattedValues["statuscode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the currency associated with the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("transactioncurrencyid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyidname")]
		public string TransactionCurrencyIdName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("transactioncurrencyid"))
				{
					return this.FormattedValues["transactioncurrencyid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UtcConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_actualhoursthisquarter")]
		public System.Nullable<decimal> Vsd_ActualHoursThisQuarter
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("vsd_actualhoursthisquarter");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_actualhoursthisquarter", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_contact")]
		public Microsoft.Xrm.Sdk.EntityReference Vsd_Contact
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("vsd_contact");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_contact", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_contactname")]
		public string Vsd_ContactName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("vsd_contact"))
				{
					return this.FormattedValues["vsd_contact"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_contactyominame")]
		public string Vsd_ContactYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("vsd_contact"))
				{
					return this.FormattedValues["vsd_contact"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_contract")]
		public Microsoft.Xrm.Sdk.EntityReference Vsd_Contract
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("vsd_contract");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_contract", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_contractedservicehrsthisquarter")]
		public System.Nullable<decimal> Vsd_ContractedServiceHrsThisQuarter
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("vsd_contractedservicehrsthisquarter");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_contractname")]
		public string Vsd_ContractName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("vsd_contract"))
				{
					return this.FormattedValues["vsd_contract"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_cpu_fiscalyear")]
		public string Vsd_Cpu_FiscalYear
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("vsd_cpu_fiscalyear");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_cpu_fiscalyear", value);
			}
		}
		
		/// <summary>
		/// The submitted schedule G quarterly report.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_cpu_reportingperiod")]
		public virtual Vsd_ScheduleG_Vsd_Cpu_ReportingPeriod? Vsd_Cpu_ReportingPeriod
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((Vsd_ScheduleG_Vsd_Cpu_ReportingPeriod?)(EntityOptionSetEnum.GetEnum(this, "vsd_cpu_reportingperiod")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_cpu_reportingperiod", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_cpu_reportingperiodname")]
		public string Vsd_Cpu_ReportingPeriodName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("vsd_cpu_reportingperiod"))
				{
					return this.FormattedValues["vsd_cpu_reportingperiod"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// The name of the custom entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_name")]
		public string Vsd_Name
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("vsd_name");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_name", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_program")]
		public Microsoft.Xrm.Sdk.EntityReference Vsd_Program
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("vsd_program");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_program", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_programadministrationbudgeted")]
		public Microsoft.Xrm.Sdk.Money Vsd_ProgramAdministrationBudgeted
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_programadministrationbudgeted");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_programadministrationbudgeted", value);
			}
		}
		
		/// <summary>
		/// Value of the Program Administration Budgeted in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_programadministrationbudgeted_base")]
		public Microsoft.Xrm.Sdk.Money Vsd_ProgramAdministrationBudgeted_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_programadministrationbudgeted_base");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_programadministrationcurrentquarter")]
		public Microsoft.Xrm.Sdk.Money Vsd_ProgramAdministrationCurrentQuarter
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_programadministrationcurrentquarter");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_programadministrationcurrentquarter", value);
			}
		}
		
		/// <summary>
		/// Value of the Program Administration Current Quarter in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_programadministrationcurrentquarter_base")]
		public Microsoft.Xrm.Sdk.Money Vsd_ProgramAdministrationCurrentQuarter_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_programadministrationcurrentquarter_base");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_programadministrationexplanation")]
		public string Vsd_ProgramAdministrationExplanation
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("vsd_programadministrationexplanation");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_programadministrationexplanation", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_programdeliverybudgeted")]
		public Microsoft.Xrm.Sdk.Money Vsd_ProgramDeliveryBudgeted
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_programdeliverybudgeted");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_programdeliverybudgeted", value);
			}
		}
		
		/// <summary>
		/// Value of the Program Delivery Budgeted in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_programdeliverybudgeted_base")]
		public Microsoft.Xrm.Sdk.Money Vsd_ProgramDeliveryBudgeted_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_programdeliverybudgeted_base");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_programdeliverycurrentquarter")]
		public Microsoft.Xrm.Sdk.Money Vsd_ProgramDeliveryCurrentQuarter
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_programdeliverycurrentquarter");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_programdeliverycurrentquarter", value);
			}
		}
		
		/// <summary>
		/// Value of the Program Delivery Current Quarter in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_programdeliverycurrentquarter_base")]
		public Microsoft.Xrm.Sdk.Money Vsd_ProgramDeliveryCurrentQuarter_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_programdeliverycurrentquarter_base");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_programdeliveryexplanations")]
		public string Vsd_ProgramDeliveryExplanations
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("vsd_programdeliveryexplanations");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_programdeliveryexplanations", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_programname")]
		public string Vsd_ProgramName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("vsd_program"))
				{
					return this.FormattedValues["vsd_program"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_quarterlybudgetedprogramadministration")]
		public Microsoft.Xrm.Sdk.Money Vsd_QuarterlyBudgetedProgramAdministration
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_quarterlybudgetedprogramadministration");
			}
		}
		
		/// <summary>
		/// Value of the Quarterly Budgeted Program Administration in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_quarterlybudgetedprogramadministration_base")]
		public Microsoft.Xrm.Sdk.Money Vsd_QuarterlyBudgetedProgramAdministration_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_quarterlybudgetedprogramadministration_base");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_quarterlybudgetedprogramdelivery")]
		public Microsoft.Xrm.Sdk.Money Vsd_QuarterlyBudgetedProgramDelivery
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_quarterlybudgetedprogramdelivery");
			}
		}
		
		/// <summary>
		/// Value of the Quarterly Budgeted Program Delivery in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_quarterlybudgetedprogramdelivery_base")]
		public Microsoft.Xrm.Sdk.Money Vsd_QuarterlyBudgetedProgramDelivery_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_quarterlybudgetedprogramdelivery_base");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_quarterlybudgetedsalariesbenefits")]
		public Microsoft.Xrm.Sdk.Money Vsd_QuarterlyBudgetedSalariesBenefits
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_quarterlybudgetedsalariesbenefits");
			}
		}
		
		/// <summary>
		/// Value of the Quarterly Budgeted Salaries & Benefits in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_quarterlybudgetedsalariesbenefits_base")]
		public Microsoft.Xrm.Sdk.Money Vsd_QuarterlyBudgetedSalariesBenefits_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_quarterlybudgetedsalariesbenefits_base");
			}
		}
		
		/// <summary>
		/// Quarterly Budgeted Amount – Actual Expenditures, Current Quarter
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_quarterlyvarianceprogramadministration")]
		public Microsoft.Xrm.Sdk.Money Vsd_QuarterlyVarianceProgramAdministration
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_quarterlyvarianceprogramadministration");
			}
		}
		
		/// <summary>
		/// Value of the Quarterly Variance Program Administration in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_quarterlyvarianceprogramadministration_base")]
		public Microsoft.Xrm.Sdk.Money Vsd_QuarterlyVarianceProgramAdministration_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_quarterlyvarianceprogramadministration_base");
			}
		}
		
		/// <summary>
		/// Quarterly Budgeted Amount – Actual Expenditures, Current Quarter
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_quarterlyvarianceprogramdelivery")]
		public Microsoft.Xrm.Sdk.Money Vsd_QuarterlyVarianceProgramDelivery
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_quarterlyvarianceprogramdelivery");
			}
		}
		
		/// <summary>
		/// Value of the Quarterly Variance Program Delivery in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_quarterlyvarianceprogramdelivery_base")]
		public Microsoft.Xrm.Sdk.Money Vsd_QuarterlyVarianceProgramDelivery_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_quarterlyvarianceprogramdelivery_base");
			}
		}
		
		/// <summary>
		/// Quarterly Budgeted Amount – Actual Expenditures, Current Quarter
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_quarterlyvariancesalariesbenefits")]
		public Microsoft.Xrm.Sdk.Money Vsd_QuarterlyVarianceSalariesBenefits
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_quarterlyvariancesalariesbenefits");
			}
		}
		
		/// <summary>
		/// Value of the Quarterly Variance Salaries & Benefits in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_quarterlyvariancesalariesbenefits_base")]
		public Microsoft.Xrm.Sdk.Money Vsd_QuarterlyVarianceSalariesBenefits_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_quarterlyvariancesalariesbenefits_base");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_reportreviewed")]
		public System.Nullable<bool> Vsd_ReportReviewed
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("vsd_reportreviewed");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_reportreviewed", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_reportreviewedname")]
		public string Vsd_ReportReviewedName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("vsd_reportreviewed"))
				{
					return this.FormattedValues["vsd_reportreviewed"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_salariesandbenefitsexplanation")]
		public string Vsd_SalariesAndBenefitsExplanation
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("vsd_salariesandbenefitsexplanation");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_salariesandbenefitsexplanation", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_salariesbenefitscurrentquarter")]
		public Microsoft.Xrm.Sdk.Money Vsd_SalariesBenefitsCurrentQuarter
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_salariesbenefitscurrentquarter");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_salariesbenefitscurrentquarter", value);
			}
		}
		
		/// <summary>
		/// Value of the Salaries & Benefits Current Quarter in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_salariesbenefitscurrentquarter_base")]
		public Microsoft.Xrm.Sdk.Money Vsd_SalariesBenefitsCurrentQuarter_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_salariesbenefitscurrentquarter_base");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_salaryandbenefitsbudgeted")]
		public Microsoft.Xrm.Sdk.Money Vsd_SalaryAndBenefitsBudgeted
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_salaryandbenefitsbudgeted");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_salaryandbenefitsbudgeted", value);
			}
		}
		
		/// <summary>
		/// Value of the Salary and Benefits Budgeted in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_salaryandbenefitsbudgeted_base")]
		public Microsoft.Xrm.Sdk.Money Vsd_SalaryAndBenefitsBudgeted_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_salaryandbenefitsbudgeted_base");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_schedulegid")]
		public System.Nullable<System.Guid> Vsd_ScheduleGId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("vsd_schedulegid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_schedulegid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_schedulegid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.Vsd_ScheduleGId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_serviceprovider")]
		public Microsoft.Xrm.Sdk.EntityReference Vsd_ServiceProvider
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("vsd_serviceprovider");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_serviceprovider", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_serviceprovidername")]
		public string Vsd_ServiceProviderName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("vsd_serviceprovider"))
				{
					return this.FormattedValues["vsd_serviceprovider"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_serviceprovideryominame")]
		public string Vsd_ServiceProviderYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("vsd_serviceprovider"))
				{
					return this.FormattedValues["vsd_serviceprovider"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_submitteddate")]
		public System.Nullable<System.DateTime> Vsd_SubmittedDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("vsd_submitteddate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_submitteddate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_sumofallyeartodatevariances")]
		public Microsoft.Xrm.Sdk.Money Vsd_SuMoFallYearToDateVariances
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_sumofallyeartodatevariances");
			}
		}
		
		/// <summary>
		/// Value of the Sum of all Year to Date Variances in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_sumofallyeartodatevariances_base")]
		public Microsoft.Xrm.Sdk.Money Vsd_SuMoFallYearToDateVariances_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_sumofallyeartodatevariances_base");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_yeartodateprogramadministration")]
		public Microsoft.Xrm.Sdk.Money Vsd_YearToDateProgramAdministration
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_yeartodateprogramadministration");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_yeartodateprogramadministration", value);
			}
		}
		
		/// <summary>
		/// Value of the Year to Date Program Administration in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_yeartodateprogramadministration_base")]
		public Microsoft.Xrm.Sdk.Money Vsd_YearToDateProgramAdministration_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_yeartodateprogramadministration_base");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_yeartodateprogramdelivery")]
		public Microsoft.Xrm.Sdk.Money Vsd_YearToDateProgramDelivery
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_yeartodateprogramdelivery");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_yeartodateprogramdelivery", value);
			}
		}
		
		/// <summary>
		/// Value of the Year to Date Program Delivery in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_yeartodateprogramdelivery_base")]
		public Microsoft.Xrm.Sdk.Money Vsd_YearToDateProgramDelivery_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_yeartodateprogramdelivery_base");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_yeartodatesalariesandbenefits")]
		public Microsoft.Xrm.Sdk.Money Vsd_YearToDatesAlAriesAndBenefits
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_yeartodatesalariesandbenefits");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_yeartodatesalariesandbenefits", value);
			}
		}
		
		/// <summary>
		/// Value of the Year to Date Salaries and Benefits in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_yeartodatesalariesandbenefits_base")]
		public Microsoft.Xrm.Sdk.Money Vsd_YearToDatesAlAriesAndBenefits_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_yeartodatesalariesandbenefits_base");
			}
		}
		
		/// <summary>
		/// Budgeted Amount – Year to Date, Expenditures, Year to Date
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_yeartodatevarianceprogramadministration")]
		public Microsoft.Xrm.Sdk.Money Vsd_YearToDateVarianceProgramAdministration
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_yeartodatevarianceprogramadministration");
			}
		}
		
		/// <summary>
		/// Value of the Year to Date Variance Program Administration in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_yeartodatevarianceprogramadministration_base")]
		public Microsoft.Xrm.Sdk.Money Vsd_YearToDateVarianceProgramAdministration_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_yeartodatevarianceprogramadministration_base");
			}
		}
		
		/// <summary>
		/// Budgeted Amount – Year to Date, Expenditures, Year to Date
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_yeartodatevarianceprogramdelivery")]
		public Microsoft.Xrm.Sdk.Money Vsd_YearToDateVarianceProgramDelivery
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_yeartodatevarianceprogramdelivery");
			}
		}
		
		/// <summary>
		/// Value of the Year to Date Variance Program Delivery in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_yeartodatevarianceprogramdelivery_base")]
		public Microsoft.Xrm.Sdk.Money Vsd_YearToDateVarianceProgramDelivery_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_yeartodatevarianceprogramdelivery_base");
			}
		}
		
		/// <summary>
		/// Budgeted Amount – Year to Date, Expenditures, Year to Date
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_yeartodatevariancesalariesbenefits")]
		public Microsoft.Xrm.Sdk.Money Vsd_YearToDateVarianceSalariesBenefits
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_yeartodatevariancesalariesbenefits");
			}
		}
		
		/// <summary>
		/// Value of the Year to Date Variance Salaries & Benefits in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_yeartodatevariancesalariesbenefits_base")]
		public Microsoft.Xrm.Sdk.Money Vsd_YearToDateVarianceSalariesBenefits_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_yeartodatevariancesalariesbenefits_base");
			}
		}
		
		/// <summary>
		/// 1:N vsd_vsd_scheduleg_task
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("vsd_vsd_scheduleg_task")]
		public System.Collections.Generic.IEnumerable<Database.Model.Task> Vsd_Vsd_ScheduleG_Task
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Database.Model.Task>("vsd_vsd_scheduleg_task", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntities<Database.Model.Task>("vsd_vsd_scheduleg_task", null, value);
			}
		}
		
		/// <summary>
		/// N:1 lk_vsd_scheduleg_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_vsd_scheduleg_createdby")]
		public Database.Model.SystemUser Lk_Vsd_ScheduleG_CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Database.Model.SystemUser>("lk_vsd_scheduleg_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_vsd_scheduleg_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_vsd_scheduleg_createdonbehalfby")]
		public Database.Model.SystemUser Lk_Vsd_ScheduleG_CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Database.Model.SystemUser>("lk_vsd_scheduleg_createdonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<Database.Model.SystemUser>("lk_vsd_scheduleg_createdonbehalfby", null, value);
			}
		}
		
		/// <summary>
		/// N:1 lk_vsd_scheduleg_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_vsd_scheduleg_modifiedby")]
		public Database.Model.SystemUser Lk_Vsd_ScheduleG_ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Database.Model.SystemUser>("lk_vsd_scheduleg_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_vsd_scheduleg_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_vsd_scheduleg_modifiedonbehalfby")]
		public Database.Model.SystemUser Lk_Vsd_ScheduleG_ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Database.Model.SystemUser>("lk_vsd_scheduleg_modifiedonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<Database.Model.SystemUser>("lk_vsd_scheduleg_modifiedonbehalfby", null, value);
			}
		}
		
		/// <summary>
		/// N:1 team_vsd_scheduleg
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_vsd_scheduleg")]
		public Database.Model.Team Team_Vsd_ScheduleG
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Database.Model.Team>("team_vsd_scheduleg", null);
			}
		}
		
		/// <summary>
		/// N:1 TransactionCurrency_vsd_scheduleg
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("TransactionCurrency_vsd_scheduleg")]
		public Database.Model.TransactionCurrency TransactionCurrency_Vsd_ScheduleG
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Database.Model.TransactionCurrency>("TransactionCurrency_vsd_scheduleg", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<Database.Model.TransactionCurrency>("TransactionCurrency_vsd_scheduleg", null, value);
			}
		}
		
		/// <summary>
		/// N:1 user_vsd_scheduleg
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_vsd_scheduleg")]
		public Database.Model.SystemUser User_Vsd_ScheduleG
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Database.Model.SystemUser>("user_vsd_scheduleg", null);
			}
		}
		
		/// <summary>
		/// N:1 vsd_account_vsd_scheduleg_ServiceProvider
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_serviceprovider")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("vsd_account_vsd_scheduleg_ServiceProvider")]
		public Database.Model.Account Vsd_Account_Vsd_ScheduleG_ServiceProvider
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Database.Model.Account>("vsd_account_vsd_scheduleg_ServiceProvider", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<Database.Model.Account>("vsd_account_vsd_scheduleg_ServiceProvider", null, value);
			}
		}
		
		/// <summary>
		/// N:1 vsd_contact_vsd_scheduleg_Contact
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_contact")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("vsd_contact_vsd_scheduleg_Contact")]
		public Database.Model.Contact Vsd_Contact_Vsd_ScheduleG_Contact
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Database.Model.Contact>("vsd_contact_vsd_scheduleg_Contact", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<Database.Model.Contact>("vsd_contact_vsd_scheduleg_Contact", null, value);
			}
		}
		
		/// <summary>
		/// N:1 vsd_vsd_contract_vsd_scheduleg_Contract
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_contract")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("vsd_vsd_contract_vsd_scheduleg_Contract")]
		public Database.Model.Vsd_Contract Vsd_Vsd_Contract_Vsd_ScheduleG_Contract
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Database.Model.Vsd_Contract>("vsd_vsd_contract_vsd_scheduleg_Contract", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<Database.Model.Vsd_Contract>("vsd_vsd_contract_vsd_scheduleg_Contract", null, value);
			}
		}
		
		/// <summary>
		/// N:1 vsd_vsd_program_vsd_scheduleg_Program
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_program")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("vsd_vsd_program_vsd_scheduleg_Program")]
		public Database.Model.Vsd_Program Vsd_Vsd_Program_Vsd_ScheduleG_Program
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Database.Model.Vsd_Program>("vsd_vsd_program_vsd_scheduleg_Program", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<Database.Model.Vsd_Program>("vsd_vsd_program_vsd_scheduleg_Program", null, value);
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public Vsd_ScheduleG(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (value != null && name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["vsd_schedulegid"] = base.Id;
                        break;
                    case "vsd_schedulegid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}
#pragma warning restore CS1591
