def PIPELINE_NAME = "cpu"

def LIB_NAME= "cpu-lib"
def LIB_REPO = "https://github.com/LayCraft/pssg-cscp-cpu.git"
def LIB_BRANCH = "development"
echo "Entering jenkins/cpu"
library identifier: "${LIB_NAME}@${LIB_BRANCH}", 
        retriever: modernSCM(
          [$class: 'GitSCMSource',
          remote: "${LIB_REPO}",
          branches: [[name: "*/${LIB_BRANCH}"]]])  

node {
  def config = load "../workspace@script/jenkins/${PIPELINE_NAME}/config.groovy"

  config.BUILDS.each {
    stage("Build ${it}") {
      script {
        openshift.withCluster() {
          openshift.withProject() {
            echo "Building the ${it} image ..."
            build(openshift, "${it}", config.WAIT_TIMEOUT)
          }
        }
      }
    }
  }

        echo "about to deploy jenkins/cpu"
  stage("Deploy ${config.DEPLOYMENT_ENVIRONMENT_TAGS[0]}") {
    script {
      deploy("${config.APP_NAME}",
             "${config.SUFFIX}",
             "${config.NAME_SPACE}",
             "${config.DEPLOYMENT_ENVIRONMENT_TAGS[0]}")
    }
  }
}
