def PIPELINE_NAME = "vsd"

def LIB_NAME= "vsd-lib"
def LIB_REPO = "https://github.com/bcgov/pssg-cscp-vsd.git"
def LIB_BRANCH = "development"
echo "Entering jenkins/vsd"
library identifier: "${LIB_NAME}@${LIB_BRANCH}", 
        retriever: modernSCM(
          [$class: 'GitSCMSource',
          remote: "${LIB_REPO}",
          branches: [[name: "*/${LIB_BRANCH}"]]])  

node {
  def config = load "../workspace@script/jenkins/${PIPELINE_NAME}/config.groovy"

  config.BUILDS.each {
    stage("Build ${it}") {
      script {
        openshift.withCluster() {
          openshift.withProject() {
            echo "Building the ${it} image ..."
            build(openshift, "${it}", config.WAIT_TIMEOUT)
          }
        }
      }
    }
  }

        echo "about to deploy jenkins/vsd to ${config.DEPLOYMENT_ENVIRONMENT_TAGS[0]}"
  stage("Deploy ${config.DEPLOYMENT_ENVIRONMENT_TAGS[0]}") {
    script {
      deploy("${config.APP_NAME}",
             "${config.SUFFIX}",
             "${config.NAME_SPACE}",
             "${config.DEPLOYMENT_ENVIRONMENT_TAGS[0]}")
    }
  }

        echo "about to deploy jenkins/vsd to ${config.DEPLOYMENT_ENVIRONMENT_TAGS[1]}"
  stage("Deploy ${config.DEPLOYMENT_ENVIRONMENT_TAGS[1]}") {
    script {
      deploy("${config.APP_NAME}",
             "${config.SUFFIX}",
             "${config.NAME_SPACE}",
             "${config.DEPLOYMENT_ENVIRONMENT_TAGS[1]}")
    }
  }

        echo "about to deploy jenkins/vsd to ${config.DEPLOYMENT_ENVIRONMENT_TAGS[2]}"
  stage("Deploy ${config.DEPLOYMENT_ENVIRONMENT_TAGS[2]}") {
    script {
      deploy("${config.APP_NAME}",
             "${config.SUFFIX}",
             "${config.NAME_SPACE}",
             "${config.DEPLOYMENT_ENVIRONMENT_TAGS[2]}")
    }
  }
}
