#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("AlmHandler")]
	public partial class ALmHandlerRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string Action = "Action";
			public const string Input = "Input";
		}
		
		public const string ActionLogicalName = "AlmHandler";
		
		public string Action
		{
			get
			{
				if (this.Parameters.Contains("action"))
				{
					return ((string)(this.Parameters["action"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["action"] = value;
			}
		}
		
		public string Input
		{
			get
			{
				if (this.Parameters.Contains("input"))
				{
					return ((string)(this.Parameters["input"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["input"] = value;
			}
		}
		
		public ALmHandlerRequest()
		{
			this.RequestName = "AlmHandler";
			this.Action = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("AlmHandler")]
	public partial class ALmHandlerResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string Result = "Result";
		}
		
		public const string ActionLogicalName = "AlmHandler";
		
		public ALmHandlerResponse()
		{
		}
		
		public string Result
		{
			get
			{
				if (this.Results.Contains("result"))
				{
					return ((string)(this.Results["result"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["result"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
