#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/bcgov/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("bcgov_ConvertSharePointDocumentToPDF")]
	public partial class Bcgov_ConvertsHaRepointDocumentToPdfRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string SharePointUrlIdScSv = "SharePointUrlIdScSv";
			public const string DesiredName = "DesiredName";
		}
		
		public const string ActionLogicalName = "bcgov_ConvertSharePointDocumentToPDF";
		
		public string SharePointUrlIdScSv
		{
			get
			{
				if (this.Parameters.Contains("SharePointUrlIdsCsv"))
				{
					return ((string)(this.Parameters["SharePointUrlIdsCsv"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SharePointUrlIdsCsv"] = value;
			}
		}
		
		public string DesiredName
		{
			get
			{
				if (this.Parameters.Contains("DesiredName"))
				{
					return ((string)(this.Parameters["DesiredName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["DesiredName"] = value;
			}
		}
		
		public Bcgov_ConvertsHaRepointDocumentToPdfRequest()
		{
			this.RequestName = "bcgov_ConvertSharePointDocumentToPDF";
			this.SharePointUrlIdScSv = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/bcgov/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("bcgov_ConvertSharePointDocumentToPDF")]
	public partial class Bcgov_ConvertsHaRepointDocumentToPdfResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string FailureCount = "FailureCount";
			public const string ProcessedCount = "ProcessedCount";
			public const string SuccessCount = "SuccessCount";
		}
		
		public const string ActionLogicalName = "bcgov_ConvertSharePointDocumentToPDF";
		
		public Bcgov_ConvertsHaRepointDocumentToPdfResponse()
		{
		}
		
		public int FailureCount
		{
			get
			{
				if (this.Results.Contains("FailureCount"))
				{
					return ((int)(this.Results["FailureCount"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Results["FailureCount"] = value;
			}
		}
		
		public int ProcessedCount
		{
			get
			{
				if (this.Results.Contains("ProcessedCount"))
				{
					return ((int)(this.Results["ProcessedCount"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Results["ProcessedCount"] = value;
			}
		}
		
		public int SuccessCount
		{
			get
			{
				if (this.Results.Contains("SuccessCount"))
				{
					return ((int)(this.Results["SuccessCount"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Results["SuccessCount"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
