#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/bcgov/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("bcgov_DownloadTemplateSchemaDefinition")]
	public partial class Bcgov_DownloadTemplateSchemaDefinitionRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string Target = "Target";
		}
		
		public const string ActionLogicalName = "bcgov_DownloadTemplateSchemaDefinition";
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public Bcgov_DownloadTemplateSchemaDefinitionRequest()
		{
			this.RequestName = "bcgov_DownloadTemplateSchemaDefinition";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/bcgov/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("bcgov_DownloadTemplateSchemaDefinition")]
	public partial class Bcgov_DownloadTemplateSchemaDefinitionResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string Body = "Body";
			public const string FileLength = "FileLength";
			public const string FileName = "FileName";
			public const string IsSuccess = "IsSuccess";
			public const string MimeType = "MimeType";
			public const string Result = "Result";
		}
		
		public const string ActionLogicalName = "bcgov_DownloadTemplateSchemaDefinition";
		
		public Bcgov_DownloadTemplateSchemaDefinitionResponse()
		{
		}
		
		public string Body
		{
			get
			{
				if (this.Results.Contains("Body"))
				{
					return ((string)(this.Results["Body"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["Body"] = value;
			}
		}
		
		public decimal FileLength
		{
			get
			{
				if (this.Results.Contains("FileLength"))
				{
					return ((decimal)(this.Results["FileLength"]));
				}
				else
				{
					return default(decimal);
				}
			}
			set
			{
				this.Results["FileLength"] = value;
			}
		}
		
		public string FileName
		{
			get
			{
				if (this.Results.Contains("FileName"))
				{
					return ((string)(this.Results["FileName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["FileName"] = value;
			}
		}
		
		public bool IsSuccess
		{
			get
			{
				if (this.Results.Contains("IsSuccess"))
				{
					return ((bool)(this.Results["IsSuccess"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Results["IsSuccess"] = value;
			}
		}
		
		public string MimeType
		{
			get
			{
				if (this.Results.Contains("MimeType"))
				{
					return ((string)(this.Results["MimeType"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["MimeType"] = value;
			}
		}
		
		public string Result
		{
			get
			{
				if (this.Results.Contains("Result"))
				{
					return ((string)(this.Results["Result"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["Result"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
