#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("CategorizeText")]
	public partial class CategorizeTextRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string Text = "Text";
			public const string ModelId = "ModelId";
			public const string Language = "Language";
		}
		
		public const string ActionLogicalName = "CategorizeText";
		
		public string Text
		{
			get
			{
				if (this.Parameters.Contains("text"))
				{
					return ((string)(this.Parameters["text"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["text"] = value;
			}
		}
		
		public string ModelId
		{
			get
			{
				if (this.Parameters.Contains("modelId"))
				{
					return ((string)(this.Parameters["modelId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["modelId"] = value;
			}
		}
		
		public string Language
		{
			get
			{
				if (this.Parameters.Contains("language"))
				{
					return ((string)(this.Parameters["language"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["language"] = value;
			}
		}
		
		public CategorizeTextRequest()
		{
			this.RequestName = "CategorizeText";
			this.Text = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("CategorizeText")]
	public partial class CategorizeTextResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string Categories = "Categories";
			public const string OriginalText = "OriginalText";
		}
		
		public const string ActionLogicalName = "CategorizeText";
		
		public CategorizeTextResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection Categories
		{
			get
			{
				if (this.Results.Contains("categories"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Results["categories"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Results["categories"] = value;
			}
		}
		
		public string OriginalText
		{
			get
			{
				if (this.Results.Contains("originalText"))
				{
					return ((string)(this.Results["originalText"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["originalText"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
