#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("DetectLanguage")]
	public partial class DetectLanguageRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string Text = "Text";
			public const string ModelId = "ModelId";
			public const string CountryHint = "CountryHint";
		}
		
		public const string ActionLogicalName = "DetectLanguage";
		
		public string Text
		{
			get
			{
				if (this.Parameters.Contains("text"))
				{
					return ((string)(this.Parameters["text"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["text"] = value;
			}
		}
		
		public string ModelId
		{
			get
			{
				if (this.Parameters.Contains("modelId"))
				{
					return ((string)(this.Parameters["modelId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["modelId"] = value;
			}
		}
		
		public string CountryHint
		{
			get
			{
				if (this.Parameters.Contains("countryHint"))
				{
					return ((string)(this.Parameters["countryHint"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["countryHint"] = value;
			}
		}
		
		public DetectLanguageRequest()
		{
			this.RequestName = "DetectLanguage";
			this.Text = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("DetectLanguage")]
	public partial class DetectLanguageResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string Language = "Language";
			public const string Score = "Score";
		}
		
		public const string ActionLogicalName = "DetectLanguage";
		
		public DetectLanguageResponse()
		{
		}
		
		public string Language
		{
			get
			{
				if (this.Results.Contains("language"))
				{
					return ((string)(this.Results["language"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["language"] = value;
			}
		}
		
		public decimal Score
		{
			get
			{
				if (this.Results.Contains("score"))
				{
					return ((decimal)(this.Results["score"]));
				}
				else
				{
					return default(decimal);
				}
			}
			set
			{
				this.Results["score"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
