#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("IsPaiEnabled")]
	public partial class IsPaiEnabledRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public const string ActionLogicalName = "IsPaiEnabled";
		
		public IsPaiEnabledRequest()
		{
			this.RequestName = "IsPaiEnabled";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("IsPaiEnabled")]
	public partial class IsPaiEnabledResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string ArePreviewScenarioEnabled = "ArePreviewScenarioEnabled";
			public const string IsDataModelV2Enabled = "IsDataModelV2Enabled";
			public const string IsPaiEnabled = "IsPaiEnabled";
			public const string PaiGaStatus = "PaiGaStatus";
			public const string Templates = "Templates";
		}
		
		public const string ActionLogicalName = "IsPaiEnabled";
		
		public IsPaiEnabledResponse()
		{
		}
		
		public bool ArePreviewScenarioEnabled
		{
			get
			{
				if (this.Results.Contains("arePreviewScenarioEnabled"))
				{
					return ((bool)(this.Results["arePreviewScenarioEnabled"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Results["arePreviewScenarioEnabled"] = value;
			}
		}
		
		public bool IsDataModelV2Enabled
		{
			get
			{
				if (this.Results.Contains("isdatamodelv2enabled"))
				{
					return ((bool)(this.Results["isdatamodelv2enabled"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Results["isdatamodelv2enabled"] = value;
			}
		}
		
		public bool IsPaiEnabled
		{
			get
			{
				if (this.Results.Contains("ispaienabled"))
				{
					return ((bool)(this.Results["ispaienabled"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Results["ispaienabled"] = value;
			}
		}
		
		public bool PaiGaStatus
		{
			get
			{
				if (this.Results.Contains("paigastatus"))
				{
					return ((bool)(this.Results["paigastatus"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Results["paigastatus"] = value;
			}
		}
		
		public string Templates
		{
			get
			{
				if (this.Results.Contains("templates"))
				{
					return ((string)(this.Results["templates"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["templates"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
