#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetAutoCaptureUri")]
	public partial class Msdyn_GetAutoCaptureUriRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string UriType = "UriType";
		}
		
		public const string ActionLogicalName = "msdyn_GetAutoCaptureUri";
		
		public string UriType
		{
			get
			{
				if (this.Parameters.Contains("uriType"))
				{
					return ((string)(this.Parameters["uriType"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["uriType"] = value;
			}
		}
		
		public Msdyn_GetAutoCaptureUriRequest()
		{
			this.RequestName = "msdyn_GetAutoCaptureUri";
			this.UriType = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetAutoCaptureUri")]
	public partial class Msdyn_GetAutoCaptureUriResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string Uri = "Uri";
		}
		
		public const string ActionLogicalName = "msdyn_GetAutoCaptureUri";
		
		public Msdyn_GetAutoCaptureUriResponse()
		{
		}
		
		public string Uri
		{
			get
			{
				if (this.Results.Contains("uri"))
				{
					return ((string)(this.Results["uri"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["uri"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
