#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_UpdateAutoCaptureSettings")]
	public partial class Msdyn_UpdateAutoCaptureSettingsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string ActionType = "ActionType";
			public const string DialogType = "DialogType";
			public const string BusinessProcessFlowId = "BusinessProcessFlowId";
			public const string BusinessProcessFlowInstanceId = "BusinessProcessFlowInstanceId";
			public const string ActionsTepid = "ActionsTepid";
		}
		
		public const string ActionLogicalName = "msdyn_UpdateAutoCaptureSettings";
		
		public int ActionType
		{
			get
			{
				if (this.Parameters.Contains("actiontype"))
				{
					return ((int)(this.Parameters["actiontype"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["actiontype"] = value;
			}
		}
		
		public int DialogType
		{
			get
			{
				if (this.Parameters.Contains("dialogtype"))
				{
					return ((int)(this.Parameters["dialogtype"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["dialogtype"] = value;
			}
		}
		
		public string BusinessProcessFlowId
		{
			get
			{
				if (this.Parameters.Contains("BusinessProcessFlowId"))
				{
					return ((string)(this.Parameters["BusinessProcessFlowId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["BusinessProcessFlowId"] = value;
			}
		}
		
		public string BusinessProcessFlowInstanceId
		{
			get
			{
				if (this.Parameters.Contains("BusinessProcessFlowInstanceId"))
				{
					return ((string)(this.Parameters["BusinessProcessFlowInstanceId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["BusinessProcessFlowInstanceId"] = value;
			}
		}
		
		public string ActionsTepid
		{
			get
			{
				if (this.Parameters.Contains("ActionStepId"))
				{
					return ((string)(this.Parameters["ActionStepId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ActionStepId"] = value;
			}
		}
		
		public Msdyn_UpdateAutoCaptureSettingsRequest()
		{
			this.RequestName = "msdyn_UpdateAutoCaptureSettings";
			this.ActionType = default(int);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_UpdateAutoCaptureSettings")]
	public partial class Msdyn_UpdateAutoCaptureSettingsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string SettingStatus = "SettingStatus";
		}
		
		public const string ActionLogicalName = "msdyn_UpdateAutoCaptureSettings";
		
		public Msdyn_UpdateAutoCaptureSettingsResponse()
		{
		}
		
		public bool SettingStatus
		{
			get
			{
				if (this.Results.Contains("settingstatus"))
				{
					return ((bool)(this.Results["settingstatus"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Results["settingstatus"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
