#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetRIProvisioningStatus")]
	public partial class Msdyn_GeTriProvisioningStatusRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public const string ActionLogicalName = "msdyn_GetRIProvisioningStatus";
		
		public Msdyn_GeTriProvisioningStatusRequest()
		{
			this.RequestName = "msdyn_GetRIProvisioningStatus";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetRIProvisioningStatus")]
	public partial class Msdyn_GeTriProvisioningStatusResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string DCIHubPlanType = "DCIHubPlanType";
			public const string EEProvisioningStatus = "EEProvisioningStatus";
			public const string RiErrorStatusCode = "RiErrorStatusCode";
			public const string RiErrorStatusMessage = "RiErrorStatusMessage";
			public const string RiProvisioningStatus = "RiProvisioningStatus";
		}
		
		public const string ActionLogicalName = "msdyn_GetRIProvisioningStatus";
		
		public Msdyn_GeTriProvisioningStatusResponse()
		{
		}
		
		public string DCIHubPlanType
		{
			get
			{
				if (this.Results.Contains("DCIHubPlanType"))
				{
					return ((string)(this.Results["DCIHubPlanType"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["DCIHubPlanType"] = value;
			}
		}
		
		public int EEProvisioningStatus
		{
			get
			{
				if (this.Results.Contains("EEProvisioningStatus"))
				{
					return ((int)(this.Results["EEProvisioningStatus"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Results["EEProvisioningStatus"] = value;
			}
		}
		
		public string RiErrorStatusCode
		{
			get
			{
				if (this.Results.Contains("RIErrorStatusCode"))
				{
					return ((string)(this.Results["RIErrorStatusCode"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["RIErrorStatusCode"] = value;
			}
		}
		
		public string RiErrorStatusMessage
		{
			get
			{
				if (this.Results.Contains("RIErrorStatusMessage"))
				{
					return ((string)(this.Results["RIErrorStatusMessage"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["RIErrorStatusMessage"] = value;
			}
		}
		
		public int RiProvisioningStatus
		{
			get
			{
				if (this.Results.Contains("RIProvisioningStatus"))
				{
					return ((int)(this.Results["RIProvisioningStatus"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Results["RIProvisioningStatus"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
