#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("ValidateAIConfiguration")]
	public partial class ValidateAIconFigurationRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string Version = "Version";
			public const string AIConfigurationId = "AIConfigurationId";
		}
		
		public const string ActionLogicalName = "ValidateAIConfiguration";
		
		public string Version
		{
			get
			{
				if (this.Parameters.Contains("version"))
				{
					return ((string)(this.Parameters["version"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["version"] = value;
			}
		}
		
		public string AIConfigurationId
		{
			get
			{
				if (this.Parameters.Contains("aiconfigurationId"))
				{
					return ((string)(this.Parameters["aiconfigurationId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["aiconfigurationId"] = value;
			}
		}
		
		public ValidateAIconFigurationRequest()
		{
			this.RequestName = "ValidateAIConfiguration";
			this.Version = default(string);
			this.AIConfigurationId = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("ValidateAIConfiguration")]
	public partial class ValidateAIconFigurationResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string Result = "Result";
		}
		
		public const string ActionLogicalName = "ValidateAIConfiguration";
		
		public ValidateAIconFigurationResponse()
		{
		}
		
		public string Result
		{
			get
			{
				if (this.Results.Contains("result"))
				{
					return ((string)(this.Results["result"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["result"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
