#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/vsd/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("vsd_GetCPUMonthlyStatisticsAnswers")]
	public partial class Vsd_GetCpuMonthlyStatisticsAnswersRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string BusinessBcEId = "BusinessBcEId";
			public const string UserBcEId = "UserBcEId";
			public const string Target = "Target";
		}
		
		public const string ActionLogicalName = "vsd_GetCPUMonthlyStatisticsAnswers";
		
		public string BusinessBcEId
		{
			get
			{
				if (this.Parameters.Contains("BusinessBCeID"))
				{
					return ((string)(this.Parameters["BusinessBCeID"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["BusinessBCeID"] = value;
			}
		}
		
		public string UserBcEId
		{
			get
			{
				if (this.Parameters.Contains("UserBCeID"))
				{
					return ((string)(this.Parameters["UserBCeID"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["UserBCeID"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public Vsd_GetCpuMonthlyStatisticsAnswersRequest()
		{
			this.RequestName = "vsd_GetCPUMonthlyStatisticsAnswers";
			this.BusinessBcEId = default(string);
			this.UserBcEId = default(string);
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/vsd/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("vsd_GetCPUMonthlyStatisticsAnswers")]
	public partial class Vsd_GetCpuMonthlyStatisticsAnswersResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string AnswerCollection = "AnswerCollection";
			public const string BusinessBcEId = "BusinessBcEId";
			public const string CategoryCollection = "CategoryCollection";
			public const string Contact = "Contact";
			public const string Contract = "Contract";
			public const string Data = "Data";
			public const string IsSuccess = "IsSuccess";
			public const string Organization = "Organization";
			public const string PortalRoles = "PortalRoles";
			public const string Program = "Program";
			public const string Result = "Result";
			public const string UserBcEId = "UserBcEId";
		}
		
		public const string ActionLogicalName = "vsd_GetCPUMonthlyStatisticsAnswers";
		
		public Vsd_GetCpuMonthlyStatisticsAnswersResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection AnswerCollection
		{
			get
			{
				if (this.Results.Contains("AnswerCollection"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Results["AnswerCollection"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Results["AnswerCollection"] = value;
			}
		}
		
		public string BusinessBcEId
		{
			get
			{
				if (this.Results.Contains("Businessbceid"))
				{
					return ((string)(this.Results["Businessbceid"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["Businessbceid"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection CategoryCollection
		{
			get
			{
				if (this.Results.Contains("CategoryCollection"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Results["CategoryCollection"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Results["CategoryCollection"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.Entity Contact
		{
			get
			{
				if (this.Results.Contains("Contact"))
				{
					return ((Microsoft.Xrm.Sdk.Entity)(this.Results["Contact"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Entity);
				}
			}
			set
			{
				this.Results["Contact"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.Entity Contract
		{
			get
			{
				if (this.Results.Contains("Contract"))
				{
					return ((Microsoft.Xrm.Sdk.Entity)(this.Results["Contract"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Entity);
				}
			}
			set
			{
				this.Results["Contract"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.Entity Data
		{
			get
			{
				if (this.Results.Contains("Data"))
				{
					return ((Microsoft.Xrm.Sdk.Entity)(this.Results["Data"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Entity);
				}
			}
			set
			{
				this.Results["Data"] = value;
			}
		}
		
		public bool IsSuccess
		{
			get
			{
				if (this.Results.Contains("IsSuccess"))
				{
					return ((bool)(this.Results["IsSuccess"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Results["IsSuccess"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.Entity Organization
		{
			get
			{
				if (this.Results.Contains("Organization"))
				{
					return ((Microsoft.Xrm.Sdk.Entity)(this.Results["Organization"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Entity);
				}
			}
			set
			{
				this.Results["Organization"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection PortalRoles
		{
			get
			{
				if (this.Results.Contains("PortalRoles"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Results["PortalRoles"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Results["PortalRoles"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.Entity Program
		{
			get
			{
				if (this.Results.Contains("Program"))
				{
					return ((Microsoft.Xrm.Sdk.Entity)(this.Results["Program"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Entity);
				}
			}
			set
			{
				this.Results["Program"] = value;
			}
		}
		
		public string Result
		{
			get
			{
				if (this.Results.Contains("Result"))
				{
					return ((string)(this.Results["Result"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["Result"] = value;
			}
		}
		
		public string UserBcEId
		{
			get
			{
				if (this.Results.Contains("Userbceid"))
				{
					return ((string)(this.Results["Userbceid"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["Userbceid"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
