/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * VSD API
 * API for the Victim Services Directory (VSD) application
 * OpenAPI spec version: v1
 */
import type { Address } from './address';

export interface AuthorizedPerson {
  authorizedPersonAgencyAddress?: Address;
  /** @nullable */
  authorizedPersonAgencyName?: string;
  /** @nullable */
  authorizedPersonEmail?: string;
  /** @nullable */
  authorizedPersonFirstName?: string;
  /** @nullable */
  authorizedPersonLastName?: string;
  /** @nullable */
  authorizedPersonPhoneNumber?: string;
  /** @nullable */
  authorizedPersonRelationship?: string;
  /** @nullable */
  authorizedPersonRelationshipOther?: string;
}
