/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * VSD API
 * API for the Victim Services Directory (VSD) application
 * OpenAPI spec version: v1
 */
import type { Courtfile } from './courtfile';
import type { Crimelocation } from './crimelocation';
import type { DocumentCollectioninformation } from './documentCollectioninformation';
import type { Offender } from './offender';
import type { Policereport } from './policereport';
import type { Racafinformation } from './racafinformation';

export interface Crimeinformation {
  /** @nullable */
  additionalOffenders?: Offender[];
  /** @nullable */
  courtFiles?: Courtfile[];
  /** @nullable */
  crimeDetails?: string;
  /** @nullable */
  crimeInjuries?: string;
  /** @nullable */
  crimeLocation?: string;
  /** @nullable */
  crimeLocations?: Crimelocation[];
  /** @nullable */
  crimePeriodEnd?: string;
  /** @nullable */
  crimePeriodStart?: string;
  /** @nullable */
  dateOfDeath?: string;
  /** @nullable */
  documents?: DocumentCollectioninformation[];
  haveYouSuedOffender?: number;
  /** @nullable */
  intendToSueOffender?: number;
  moreThanOneOffender?: boolean;
  /** @nullable */
  noPoliceReportIdentification?: string;
  /** @nullable */
  offenderBeenCharged?: number;
  /** @nullable */
  offenderFirstName?: string;
  /** @nullable */
  offenderLastName?: string;
  /** @nullable */
  offenderMiddleName?: string;
  /** @nullable */
  offenderRelationship?: string;
  /** @nullable */
  overOneYearFromCrime?: number;
  /** @nullable */
  policeReportedMultipleTimes?: string;
  /** @nullable */
  policeReports?: Policereport[];
  racafInformation?: Racafinformation;
  /** @nullable */
  typeOfCrime?: string;
  unsureOfCrimeDates?: boolean;
  /** @nullable */
  victimDeceasedFromCrime?: number;
  /** @nullable */
  wasReportMadeToPolice?: number;
  /** @nullable */
  whenDidCrimeOccur?: string;
  /** @nullable */
  whyDidYouNotApplySooner?: string;
}
