/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * VSD API
 * API for the Victim Services Directory (VSD) application
 * OpenAPI spec version: v1
 */
import type { DocumentCollectioninformation } from './documentCollectioninformation';
import type { Employer } from './employer';

export interface Employmentincomeinformation {
  /** @nullable */
  areYouSelfEmployed?: number;
  /** @nullable */
  areYouStillOffWork?: number;
  /** @nullable */
  daysWorkMissedEnd?: string;
  /** @nullable */
  daysWorkMissedStart?: string;
  /** @nullable */
  didYouLoseWages?: number;
  /** @nullable */
  didYouMissWorkDueToCrime?: number;
  /** @nullable */
  documents?: DocumentCollectioninformation[];
  /** @nullable */
  employers?: Employer[];
  /** @nullable */
  haveYouAppliedForWorkersCompensation?: string;
  /** @nullable */
  mayContactEmployer?: number;
  /** @nullable */
  wereYouAtWorkAtTimeOfIncident?: number;
  /** @nullable */
  wereYouEmployedAtTimeOfCrime?: number;
  /** @nullable */
  workersCompensationClaimNumber?: string;
}
