/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * VSD API
 * API for the Victim Services Directory (VSD) application
 * OpenAPI spec version: v1
 */
import type { Employer } from './employer';

export interface Expenseinformation {
  /** @nullable */
  additionalBenefitsDetails?: string;
  /** @nullable */
  daysWorkMissedEnd?: string;
  /** @nullable */
  daysWorkMissedStart?: string;
  /** @nullable */
  didYouLoseWages?: number;
  /** @nullable */
  employers?: Employer[];
  haveAboriginalAffairsAndNorthernDevelopmentCanadaBenefits?: boolean;
  haveBereavementLeaveExpenses?: boolean;
  haveCanadaPensionPlanBenefits?: boolean;
  haveChildcareExpenses?: boolean;
  haveCivilActionBenefits?: boolean;
  haveCounsellingExpenses?: boolean;
  haveCounsellingTransportation?: boolean;
  haveCrimeSceneCleaningExpenses?: boolean;
  haveDentalExpenses?: boolean;
  haveDisabilityExpenses?: boolean;
  haveDisabilityPlanBenefits?: boolean;
  haveEmploymentInsuranceBenefits?: boolean;
  haveFuneralExpenses?: boolean;
  haveHomeMakerExpenses?: boolean;
  haveIncomeAssistanceBenefits?: boolean;
  haveIncomeSupportExpenses?: boolean;
  haveLegalProceedingExpenses?: boolean;
  haveLifeInsuranceBenefits?: boolean;
  haveLostEmploymentIncomeExpenses?: boolean;
  haveLostOfParentalGuidanceExpenses?: boolean;
  haveMedicalExpenses?: boolean;
  haveMovingExpenses?: boolean;
  haveOtherBenefits?: boolean;
  haveOtherExpenses?: boolean;
  havePersonalPropertyLostExpenses?: boolean;
  havePrescriptionDrugExpenses?: boolean;
  haveProtectiveMeasureExpenses?: boolean;
  haveProtectiveMovingExpenses?: boolean;
  haveTransportationToObtainBenefits?: boolean;
  haveVocationalServicesExpenses?: boolean;
  /** @nullable */
  mayContactEmployer?: number;
  /** @nullable */
  missedWorkDueToDeathOfVictim?: number;
  noneOfTheAboveBenefits?: boolean;
  /** @nullable */
  otherSpecificBenefits?: string;
  /** @nullable */
  otherSpecificExpenses?: string;
}
