/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * VSD API
 * API for the Victim Services Directory (VSD) application
 * OpenAPI spec version: v1
 */
import type { CounsellingType } from './counsellingType';

export interface InvoiceLineItemDto {
  /** @nullable */
  attendingSupportPerson?: string;
  counsellingType: CounsellingType;
  /** @nullable */
  counsellingTypeName?: string;
  missedSession?: boolean;
  /** @nullable */
  sessionAmount?: number;
  sessionDate: string;
  sessionHours: number;
}
