/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * VSD API
 * API for the Victim Services Directory (VSD) application
 * OpenAPI spec version: v1
 */
import type { DocumentDto } from './documentDto';
import type { InvoiceDetailsDto } from './invoiceDetailsDto';

export interface InvoiceDto {
  /** @nullable */
  documentCollection?: DocumentDto[];
  invoiceDetails?: InvoiceDetailsDto;
}
