/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * VSD API
 * API for the Victim Services Directory (VSD) application
 * OpenAPI spec version: v1
 */
import type { InvoiceLineItemDto } from './invoiceLineItemDto';

export interface InvoiceDetailsDto {
  /** @minLength 1 */
  claimantFirstName: string;
  /** @minLength 1 */
  claimantLastName: string;
  /** @minLength 1 */
  claimNumber: string;
  /** @minLength 1 */
  counselorLastName: string;
  /** @minLength 1 */
  counselorNumber: string;
  exemptFromGst?: boolean;
  invoicedAte: string;
  /** @nullable */
  invoiceLineItems?: InvoiceLineItemDto[];
  /** @minLength 1 */
  invoiceNumber: string;
  /** @minLength 1 */
  submitterEmailAddress: string;
  /** @minLength 1 */
  submitterFullName: string;
  /** @minLength 1 */
  vendorNumber: string;
  /** @minLength 1 */
  vendorPostalCode: string;
}
