/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * VSD API
 * API for the Victim Services Directory (VSD) application
 * OpenAPI spec version: v1
 */

export interface LoginRequest {
  /** @minLength 1 */
  password: string;
  /** @minLength 1 */
  username: string;
}
