/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * VSD API
 * API for the Victim Services Directory (VSD) application
 * OpenAPI spec version: v1
 */
import type { Address } from './address';
import type { Othertreatment } from './othertreatment';

export interface Medicalinformation {
  /** @minLength 1 */
  beingTreatedByFamilyDoctor: string;
  /** @minLength 1 */
  doYouHaveMedicalServicesCoverage: string;
  doYouHaveOtherHealthCoverage: number;
  familyDoctorAddress?: Address;
  /** @nullable */
  familyDoctorClinic?: string;
  /** @nullable */
  familyDoctorEmail?: string;
  /** @nullable */
  familyDoctorFax?: string;
  /** @nullable */
  familyDoctorFirstName?: string;
  /** @nullable */
  familyDoctorLastName?: string;
  /** @nullable */
  familyDoctorPhoneNumber?: string;
  /** @minLength 1 */
  hadOtherTreatments: string;
  /** @nullable */
  haveMedicalCoverageProvince?: string;
  /** @nullable */
  haveMedicalCoverageProvinceOther?: string;
  /** @nullable */
  otherHealthCoverageExtendedPlanNumber?: string;
  /** @nullable */
  otherHealthCoverageProviderName?: string;
  /** @nullable */
  otherTreatments?: Othertreatment[];
  /** @nullable */
  personalHealthNumber?: string;
  /** @nullable */
  treatedAtHospitalDate?: string;
  /** @nullable */
  treatedAtHospitalName?: string;
  treatedOutsideBc?: boolean;
  /** @nullable */
  treatedOutsideBcHospitalName?: string;
  /** @nullable */
  wereYouTreatedAtHospital?: string;
}
