/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * VSD API
 * API for the Victim Services Directory (VSD) application
 * OpenAPI spec version: v1
 */
import type { Address } from './address';
import type { DocumentCollectioninformation } from './documentCollectioninformation';

export interface Representativeinformation {
  completingOnBehalfOf: number;
  /** @nullable */
  documents?: DocumentCollectioninformation[];
  /** @nullable */
  relationshipToPerson?: string;
  representativeAddress?: Address;
  /** @nullable */
  representativeAlternatePhoneNumber?: string;
  /** @nullable */
  representativeEmail?: string;
  /** @nullable */
  representativeFirstName?: string;
  /** @nullable */
  representativeLastName?: string;
  /** @nullable */
  representativeMiddleName?: string;
  /** @nullable */
  representativePhoneNumber?: string;
  /** @nullable */
  representativePreferredMethodOfContact?: number;
}
