/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * VSD API
 * API for the Victim Services Directory (VSD) application
 * OpenAPI spec version: v1
 */
import type { Address } from './address';

export interface VictimInformation {
  /** @nullable */
  alternatePhoneNumber?: string;
  /** @nullable */
  birthDate?: string;
  /** @nullable */
  dateOfNameChange?: string;
  /** @nullable */
  email?: string;
  /** @nullable */
  firstName?: string;
  /** @nullable */
  gender?: number;
  /** @nullable */
  iHaveOtherNames?: string;
  /** @nullable */
  indigenousStatus?: number;
  /** @nullable */
  lastName?: string;
  /** @nullable */
  maritalStatus?: number;
  /** @nullable */
  middleName?: string;
  /** @nullable */
  occupation?: string;
  /** @nullable */
  otherFirstName?: string;
  /** @nullable */
  otherGender?: string;
  /** @nullable */
  otherLastName?: string;
  /** @nullable */
  otherPronouns?: string;
  /** @nullable */
  otherRaceEthnicity?: string;
  /** @nullable */
  phoneNumber?: string;
  primaryAddress?: Address;
  /** @nullable */
  pronouns?: number;
  /** @nullable */
  raceEthnicity?: number;
  /** @nullable */
  sin?: string;
}
