# ======================================================================================
#  Last Updated: 2025-07-23
#
#  Description:
#  This is the main CD workflow for the Application.
#  It orchestrates the build and deployment process for the API and UI services.
#
#  Triggers:
#  1. Automatic (`workflow_run`): Triggers automatically after the 'CI job'
#     workflow completes successfully on the 'development' branch.
#  2. Manual (`workflow_dispatch`): Allows for manual deployments to the 'development'
#     branch. Requires a 7-character commit SHA.
#
#  Git Event Payload testing:
#      - name: Dump push event
#        run: cat $GITHUB_EVENT_PATH
#
#  act workflow_dispatch -W .github/workflows/cd-vsd.yml --dryrun --env GITHUB_REPOSITORY="bcgov/pssg-cscp-vsd" --bind
# ======================================================================================

name: CD VSD

# --- TRIGGERS -----------------------------------------------------------------------
on:
  # Triggers this workflow after the CI workflow completes on the development branch
  workflow_run:
    workflows: ["CI VSD"]
    types:
      - completed

  # manual trigger
  workflow_dispatch:
    inputs:
      short_merge_commit_sha:
        description: "Optional: Short merge commit SHA"
        required: false

# --- JOBS ---------------------------------------------------------------------------
jobs:
  # ------------------------------------------------------------------------------------
  #  Purpose: Determine the correct tag to be used for the build.
  #           - For CI triggers: uses the 7-character commit SHA.
  #           - For manual triggers: uses the provided SHA, or 'manual' if none is provided.
  #  Outputs:
  #    - short_sha: The validated 7-character commit SHA or 'manual' for manual runs without SHA.
  # ------------------------------------------------------------------------------------
  prepare-build-params:
    runs-on: ubuntu-latest
    # This job will only run if the triggering CI workflow was successful
    if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'
    outputs:
      short_sha: ${{ steps.determine-sha-from-workflow-run.outputs.short_sha || steps.validate-manual-sha.outputs.short_sha }}
    steps:
      # This step handles the automated trigger from the CI workflow
      - name: Extract Commit SHA from CI Workflow
        id: determine-sha-from-workflow-run
        if: github.event_name == 'workflow_run'
        run: |
          # The workflow_run event provides the exact commit SHA from the completed CI run.
          COMMIT_SHA="${{ github.event.workflow_run.head_sha }}"
          echo "Triggering commit from CI workflow: $COMMIT_SHA"
          echo "short_sha=$(echo $COMMIT_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      # This step handles the manual trigger
      - name: Validate Manual Trigger SHA
        id: validate-manual-sha
        if: github.event_name == 'workflow_dispatch'
        run: |
          SHORT_SHA="${{ github.event.inputs.short_merge_commit_sha }}"
          if [[ -z "$SHORT_SHA" ]]; then
            SHORT_SHA="manual"
          elif [[ ! "$SHORT_SHA" =~ ^[a-fA-F0-9]{7}$ ]]; then
            echo "::error::SHA must be exactly 7 hexadecimal characters. Received: '$SHORT_SHA'"
            exit 1
          fi
          echo "short_sha=$SHORT_SHA" >> $GITHUB_OUTPUT

  # ------------------------------------------------------------------------------------
  #  Job: build-and-deploy
  #  Purpose: Calls the reusable build workflow to build, publish, and scan the image.
  # ------------------------------------------------------------------------------------
  build-and-deploy-ui:
    needs: prepare-build-params
    permissions:
      contents: read
      packages: write
      id-token: write # Required for environment protection
      security-events: write
    uses: ./.github/workflows/build-template.yml
    with:
      EVENT_NAME: ${{ github.event_name }}
      IMAGE_CONTEXT: ./
      IMAGE_FILE: ./vsd-app/ClientApp/Dockerfile
      IMAGE_NAME: vsd-ui
      REGISTRY: ${{ vars.OCP4_REGISTRY }}
      BRANCH: ${{ github.ref_name }}
      # Use the output from pr job
      COMMIT_SHA: ${{ needs.prepare-build-params.outputs.short_sha }}
    secrets:
      REGISTRY_USER: ${{ secrets.OCP4_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.OCP4_PASSWORD }}

  build-and-deploy-api:
    needs: prepare-build-params
    permissions:
      contents: read
      packages: write
      id-token: write # Required for environment protection
      security-events: write
    uses: ./.github/workflows/build-template.yml
    with:
      EVENT_NAME: ${{ github.event_name }}
      IMAGE_CONTEXT: ./
      IMAGE_FILE: ./vsd-app/Dockerfile
      IMAGE_NAME: vsd-api
      REGISTRY: ${{ vars.OCP4_REGISTRY }}
      BRANCH: ${{ github.ref_name }}
      # Use the output from pr job
      COMMIT_SHA: ${{ needs.prepare-build-params.outputs.short_sha }}
    secrets:
      REGISTRY_USER: ${{ secrets.OCP4_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.OCP4_PASSWORD }}
