name: cd-ZAP

on:
  workflow_dispatch:

env:
  APP_NAME: vsd
  BUILD_ID: ${{ github.server_url }}!${{ github.repository }}!${{ github.ref_name }}!${{ github.sha }}!${{ github.run_number }}
  IMAGE_REGISTRY: ${{ secrets.OCP4_REGISTRY }}/${{ secrets.OCP4_NAMESPACE }}

jobs:
  build-vsd-zap:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'bcgov'
    env:
      IMAGE_NAME: zap
      VSD_ZAP_DOCKERFILE_PATH: ./Dockerfile

    steps:
      - uses: actions/checkout@v4

      - name: Dump all environment variables
        run: printenv | sort

      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'

      - name: Set up Docker Buildx tooling
        uses: docker/setup-buildx-action@v3

      - name: Log into OpenShift Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ secrets.OCP4_USERNAME }}
          password: ${{ secrets.OCP4_PASSWORD }}

      - name: Pull image
        run: docker pull ${{ env.IMAGE_REGISTRY }}/${{ env.APP_NAME }}-${{ env.IMAGE_NAME }}:dev || true

      - name: Bump version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ${{ env.APP_NAME }}-${{ env.IMAGE_NAME }}=v
          fetch_all_tags: true

      - name: Create version env var
        run: echo "BUILD_VERSION=$(echo '${{ steps.tag_version.outputs.new_tag }}' | awk -F-v '{print $NF}')" >> $GITHUB_ENV
 

      - name: Build and push vsd-zap
        uses: docker/build-push-action@v6
        with:
          build-args: |
            BUILD_ID="${{ env.BUILD_ID }}"
            BUILD_VERSION=${{ env.BUILD_VERSION }}
          cache-from: |
            ${{ env.IMAGE_REGISTRY }}/${{ env.APP_NAME }}-${{ env.IMAGE_NAME }}
          file: ${{ env.VSD_ZAP_DOCKERFILE_PATH }}
          push: true
          tags: |
            ${{ env.IMAGE_REGISTRY }}/${{ env.APP_NAME }}-${{ env.IMAGE_NAME }}:dev

      - name: Save image as tarball for Trivy
        run: |
          docker save "$IMAGE_REGISTRY/$APP_NAME-$IMAGE_NAME:dev" -o "$APP_NAME-$IMAGE_NAME.tar"

      - name: Install Trivy
        run: |
          wget -qO- https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | bash
          echo "$(pwd)/bin" >> $GITHUB_PATH

      - name: Trivy scan for vsd zap image
        continue-on-error: true
        run: |
          trivy image --input "$APP_NAME-$IMAGE_NAME.tar" \
            --severity HIGH,CRITICAL \
            --ignore-unfixed \
            --exit-code 1 \
            --format sarif \
            --output trivy-$APP_NAME-$IMAGE_NAME-image-scan.sarif

      - name: Upload scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-${{ env.APP_NAME }}-${{ env.IMAGE_NAME }}-image-scan.sarif
          category: trivy-built-image-scan-results