name: ZAP Full Scan - Internal

on:
  workflow_dispatch:

jobs:
  zap-full-ui-api:
    name: ZAP Full Scan from Self-Hosted Runner
    runs-on: self-hosted

    strategy:
      matrix:
        include:
          - name: vsd-ui
            url: https://coast-vsd-dev.silver.devops.bcgov
            type: ui

    steps:
      - name: Full Scan UI
        if: matrix.type == 'ui'
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: ${{ matrix.url }}
          allow_issue_writing: false
          issue_title: "zap-full-ui-${{ matrix.name }}"
          artifact_name: "zap-full-ui-${{ matrix.name }}"
          